# CSE602: Machine Learning - I

# Challenge 1

### Submitted by:
#### Name      : Muhammad Amin Ghias
#### ERP ID    : 25366

Date : 24th Feb 2022

# ML-1 Challenge1 House Price Prediction - Inspired from Russian Housing

## Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.feature_selection import SequentialFeatureSelector
import os

import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np

from sklearn.preprocessing import PolynomialFeatures

from sklearn.linear_model import RidgeCV
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from numpy import arange
from sklearn.linear_model import LassoCV
import warnings 
warnings.filterwarnings('ignore')

from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from numpy import mean
from sklearn.feature_selection import SequentialFeatureSelector

from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor


from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from numpy import mean



cv = KFold(n_splits=10, random_state=1, shuffle=True)
reg = LinearRegression()

## Loading datasets

In [14]:
df=pd.read_csv('train.csv')

In [15]:
df.shape

(181507, 272)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181507 entries, 0 to 181506
Columns: 272 entries, full_sq to price_doc
dtypes: float64(257), object(15)
memory usage: 376.7+ MB

In [17]:
df.info

<bound method DataFrame.info of         full_sq  life_sq  floor product_type                        sub_area  \
0          43.0     27.0    4.0   Investment                        Bibirevo
1          34.0     19.0    3.0   Investment               Nagatinskij Zaton
2          43.0     29.0    2.0   Investment                  Tekstil'shhiki
3          77.0     77.0    4.0   Investment                       Basmannoe
4          67.0     46.0   14.0   Investment                  Nizhegorodskoe
...         ...      ...    ...          ...                             ...
181502     48.0     33.0    3.0   Investment  Poselenie Mihajlovo-Jarcevskoe
181503     48.0     33.0    3.0   Investment  Poselenie Mihajlovo-Jarcevskoe
181504     48.0     33.0    3.0   Investment  Poselenie Mihajlovo-Jarcevskoe
181505     48.0     33.0    3.0   Investment  Poselenie Mihajlovo-Jarcevskoe
181506     48.0     33.0    3.0   Investment  Poselenie Mihajlovo-Jarcevskoe

              area_m  raion_popul  green_zone_part  indust_part  \
0       6.407578e+06     155572.0         0.189727     0.000070
1       9.589337e+06     115352.0         0.372602     0.049637
2       4.808270e+06     101708.0         0.112560     0.118537
3       8.398461e+06     108171.0         0.015234     0.037316
4       7.506452e+06      43795.0         0.007670     0.486246
...              ...          ...              ...          ...
181502  6.455617e+07       4949.0         0.586175     0.005819
181503  6.455617e+07       4949.0         0.586175     0.005819
181504  6.455617e+07       4949.0         0.586175     0.005819
181505  6.455617e+07       4949.0         0.586175     0.005819
181506  6.455617e+07       4949.0         0.586175     0.005819

        children_preschool  ...  cafe_count_5000_price_2500  \
0                   9576.0  ...                         9.0
1                   6880.0  ...                        15.0
2                   5879.0  ...                        10.0
3                   5706.0  ...                       319.0
4                   2418.0  ...                        62.0
...                    ...  ...                         ...
181502               346.0  ...                         0.0
181503               346.0  ...                         0.0
181504               346.0  ...                         0.0
181505               346.0  ...                         0.0
181506               346.0  ...                         0.0

        cafe_count_5000_price_4000  cafe_count_5000_price_high  \
0                              4.0                         0.0
1                              3.0                         0.0
2                              3.0                         0.0
3                            108.0                        17.0
4                             14.0                         1.0
...                            ...                         ...
181502                         0.0                         0.0
181503                         0.0                         0.0
181504                         0.0                         0.0
181505                         0.0                         0.0
181506                         0.0                         0.0

        big_church_count_5000  church_count_5000  mosque_count_5000  \
0                        13.0               22.0                1.0
1                        15.0               29.0                1.0
2                        11.0               27.0                0.0
3                       135.0              236.0                2.0
4                        53.0               78.0                1.0
...                       ...                ...                ...
181502                    0.0                2.0                0.0
181503                    0.0                2.0                0.0
181504                    0.0                2.0                0.0
181505                    0.0                2.0                0.0
181506                    0.0                2.0                0.0

        leisure_count_5000  sport_count_5000 market_count_5000   price_doc
0                      0.0              52.0               4.0   5850000.0
1                     10.0              66.0              14.0   6000000.0
2                      4.0              67.0              10.0   5700000.0
3                     91.0             195.0              14.0  16331452.0
4                     20.0             113.0              17.0   9100000.0
...                    ...               ...               ...         ...
181502                 0.0               0.0               0.0   3480000.0
181503                 0.0               0.0               0.0   3480000.0
181504                 0.0               0.0               0.0   3480000.0
181505                 0.0               0.0               0.0   3480000.0
181506                 0.0               0.0               0.0   3480000.0

[181507 rows x 272 columns]>

In [18]:
df.dtypes

full_sq               float64
life_sq               float64
floor                 float64
product_type           object
sub_area               object
                       ...
mosque_count_5000     float64
leisure_count_5000    float64
sport_count_5000      float64
market_count_5000     float64
price_doc             float64
Length: 272, dtype: object

In [19]:
df.describe()

,full_sq,life_sq,floor,area_m,raion_popul,green_zone_part,indust_part,children_preschool,preschool_education_centers_raion,children_school,...,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc
count,181507.000000,181507.000000,181507.000000,1.815070e+05,181507.000000,181507.000000,181507.000000,181507.000000,181507.000000,181507.000000,...,181507.000000,181507.000000,181507.000000,181507.000000,181507.000000,181507.000000,181507.000000,181507.000000,181507.000000,1.815070e+05
mean,448.328579,591.966690,11.607829,3.051875e+07,87217.474849,0.241177,0.143175,5481.379439,4.235794,5655.051760,...,66.525929,23.993228,4.498168,28.250146,51.063084,0.573885,18.187312,70.773508,7.454480,1.475129e+07
std,1111.378930,1505.681491,14.768439,4.739800e+07,55519.596237,0.213479,0.141066,3975.876352,2.934349,4046.925781,...,101.601320,40.111305,8.054897,39.726282,64.104277,0.640763,28.522453,53.997656,5.206001,2.183308e+07
min,0.000000,0.000000,0.000000,2.081628e+06,2546.000000,0.001879,0.000000,175.000000,0.000000,168.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+05
25%,40.226320,24.029214,3.907741,5.646405e+06,43795.000000,0.065444,0.018244,2510.000000,2.000000,2787.000000,...,5.824950,1.000000,0.000000,5.000000,11.000000,0.000000,1.000000,29.934456,3.000000,5.074068e+06
50%,52.964840,33.688075,6.792178,9.249237e+06,83369.000000,0.167526,0.096720,4857.000000,4.000000,5048.000000,...,14.931993,3.867277,0.000000,10.000000,24.000000,0.253875,4.000000,62.225832,7.000000,6.990491e+06
75%,76.518358,63.000000,11.598490,2.420039e+07,118945.000000,0.372602,0.232205,7104.000000,6.000000,7425.000000,...,73.485273,21.033735,4.238575,29.268709,57.000000,1.000000,19.410651,100.711931,11.908096,1.164078e+07
max,5326.000000,7478.000000,76.998630,2.060718e+08,247469.000000,0.852923,0.521867,19223.000000,13.000000,19083.000000,...,377.000000,147.000000,30.000000,151.000000,250.000000,2.000000,106.000000,218.000000,20.999423,1.111111e+08

In [20]:
df.head()

,full_sq,life_sq,floor,product_type,sub_area,area_m,raion_popul,green_zone_part,indust_part,children_preschool,...,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc
0,43.0,27.0,4.0,Investment,Bibirevo,6407578.100,155572.0,0.189727,0.000070,9576.0,...,9.0,4.0,0.0,13.0,22.0,1.0,0.0,52.0,4.0,5850000.0
1,34.0,19.0,3.0,Investment,Nagatinskij Zaton,9589336.912,115352.0,0.372602,0.049637,6880.0,...,15.0,3.0,0.0,15.0,29.0,1.0,10.0,66.0,14.0,6000000.0
2,43.0,29.0,2.0,Investment,Tekstil'shhiki,4808269.831,101708.0,0.112560,0.118537,5879.0,...,10.0,3.0,0.0,11.0,27.0,0.0,4.0,67.0,10.0,5700000.0
3,77.0,77.0,4.0,Investment,Basmannoe,8398460.622,108171.0,0.015234,0.037316,5706.0,...,319.0,108.0,17.0,135.0,236.0,2.0,91.0,195.0,14.0,16331452.0
4,67.0,46.0,14.0,Investment,Nizhegorodskoe,7506452.020,43795.0,0.007670,0.486246,2418.0,...,62.0,14.0,1.0,53.0,78.0,1.0,20.0,113.0,17.0,9100000.0

### Formulating dataset into all float continuous values and finding test objects

In [21]:
def dataset_objs(dataset):
    df=dataset
    d=df.dtypes
    type(d)
    d
    cl=d[d==object]
    cl
    cli=cl.index
    cli[0]
    type(cli)
    (cl.index)


    col__obj=[]
    col_objrem=[]
    c=0

    for i in cli:
        v=df[i].unique()
        # print(v)
        col_objrem.append(i)
        col__obj.append([i,v,len(v)])

        print(i,":",col__obj[c],"count :",len(v))
        c=c+1
    return(col__obj)

In [22]:
df_obj=dataset_objs(df)

product_type : ['product_type', array(['Investment', 'OwnerOccupier'], dtype=object), 2] count : 2
sub_area : ['sub_area', array(['Bibirevo', 'Nagatinskij Zaton', "Tekstil'shhiki", ...,
       'Poselenie iMhajlovo-Jarcevskoe', 'Poselenie Mihajlovo-Jracevskoe',
       'Poselenie Mhiajlovo-Jarcevskoe'], dtype=object), 1927] count : 1927
culture_objects_top_25 : ['culture_objects_top_25', array(['no', 'yes'], dtype=object), 2] count : 2
thermal_power_plant_raion : ['thermal_power_plant_raion', array(['no', 'yes'], dtype=object), 2] count : 2
incineration_raion : ['incineration_raion', array(['no', 'yes'], dtype=object), 2] count : 2
oil_chemistry_raion : ['oil_chemistry_raion', array(['no', 'yes'], dtype=object), 2] count : 2
radiation_raion : ['radiation_raion', array(['no', 'yes'], dtype=object), 2] count : 2
railroad_terminal_raion : ['railroad_terminal_raion', array(['no', 'yes'], dtype=object), 2] count : 2
big_market_raion : ['big_market_raion', array(['no', 'yes'], dtype=object), 2] count : 2
nuclear_reactor_raion : ['nuclear_reactor_raion', array(['no', 'yes'], dtype=object), 2] count : 2
detention_facility_raion : ['detention_facility_raion', array(['no', 'yes'], dtype=object), 2] count : 2
water_1line : ['water_1line', array(['no', 'yes'], dtype=object), 2] count : 2
big_road1_1line : ['big_road1_1line', array(['no', 'yes'], dtype=object), 2] count : 2
railroad_1line : ['railroad_1line', array(['no', 'yes'], dtype=object), 2] count : 2
ecology : ['ecology', array(['good', 'excellent', 'poor', 'satisfactory', 'no data'],
      dtype=object), 5] count : 5

This shows our dataset has objects in its columns out of which sub_area feaure had 1927 distinct sub-types
this will make dataset very large when we use onehot encoding so we remove sub_area feature

## Formulating X and y

In [23]:
dfX=df.copy()
dfX=dfX.drop(columns=['sub_area','price_doc'])
print(dfX.shape)
dfX.head()

(181507, 270)

,full_sq,life_sq,floor,product_type,area_m,raion_popul,green_zone_part,indust_part,children_preschool,preschool_education_centers_raion,...,cafe_count_5000_price_1500,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000
0,43.0,27.0,4.0,Investment,6407578.100,155572.0,0.189727,0.000070,9576.0,5.0,...,40.0,9.0,4.0,0.0,13.0,22.0,1.0,0.0,52.0,4.0
1,34.0,19.0,3.0,Investment,9589336.912,115352.0,0.372602,0.049637,6880.0,5.0,...,36.0,15.0,3.0,0.0,15.0,29.0,1.0,10.0,66.0,14.0
2,43.0,29.0,2.0,Investment,4808269.831,101708.0,0.112560,0.118537,5879.0,4.0,...,25.0,10.0,3.0,0.0,11.0,27.0,0.0,4.0,67.0,10.0
3,77.0,77.0,4.0,Investment,8398460.622,108171.0,0.015234,0.037316,5706.0,7.0,...,552.0,319.0,108.0,17.0,135.0,236.0,2.0,91.0,195.0,14.0
4,67.0,46.0,14.0,Investment,7506452.020,43795.0,0.007670,0.486246,2418.0,2.0,...,155.0,62.0,14.0,1.0,53.0,78.0,1.0,20.0,113.0,17.0

Applying onehot encoding to convert classes into continuous value

In [24]:
X = pd.get_dummies(dfX)
print(X.shape)
X.head()

(181507, 287)

,full_sq,life_sq,floor,area_m,raion_popul,green_zone_part,indust_part,children_preschool,preschool_education_centers_raion,children_school,...,water_1line_yes,big_road1_1line_no,big_road1_1line_yes,railroad_1line_no,railroad_1line_yes,ecology_excellent,ecology_good,ecology_no data,ecology_poor,ecology_satisfactory
0,43.0,27.0,4.0,6407578.100,155572.0,0.189727,0.000070,9576.0,5.0,10309.0,...,0,1,0,1,0,0,1,0,0,0
1,34.0,19.0,3.0,9589336.912,115352.0,0.372602,0.049637,6880.0,5.0,7759.0,...,0,1,0,1,0,1,0,0,0,0
2,43.0,29.0,2.0,4808269.831,101708.0,0.112560,0.118537,5879.0,4.0,6207.0,...,0,1,0,1,0,0,0,0,1,0
3,77.0,77.0,4.0,8398460.622,108171.0,0.015234,0.037316,5706.0,7.0,6748.0,...,0,1,0,0,1,1,0,0,0,0
4,67.0,46.0,14.0,7506452.020,43795.0,0.007670,0.486246,2418.0,2.0,2514.0,...,0,1,0,1,0,0,0,0,1,0

In [25]:
y=df['price_doc']
y.head()

0     5850000.0
1     6000000.0
2     5700000.0
3    16331452.0
4     9100000.0
Name: price_doc, dtype: float64

In [26]:
df.shape

(181507, 272)

## Formulating training dataset

In [27]:
df_test=pd.read_csv('test.csv')
print(df_test.shape)
dfXt=df_test.copy()
dfXt=dfXt.drop(columns=['sub_area','row ID'])
print(dfXt.shape)
dfXt.head()

(77789, 272)
(77789, 270)

,full_sq,life_sq,floor,product_type,area_m,raion_popul,green_zone_part,indust_part,children_preschool,preschool_education_centers_raion,...,cafe_count_5000_price_1500,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000
0,89.0,50.0,9.0,Investment,1.258354e+07,178473.0,0.194703,0.069753,13087.0,9.0,...,15.0,11.0,2.0,1.0,4.0,4.0,0.0,0.0,26.0,3.0
1,25.0,14.0,10.0,Investment,1.032047e+07,57405.0,0.523439,0.042307,2459.0,5.0,...,144.0,81.0,16.0,3.0,38.0,80.0,1.0,27.0,127.0,8.0
2,38.0,19.0,11.0,Investment,7.632940e+06,78810.0,0.051844,0.437885,5519.0,3.0,...,39.0,8.0,3.0,0.0,10.0,9.0,0.0,0.0,35.0,4.0
3,43.0,28.0,4.0,Investment,5.235177e+07,142462.0,0.070662,0.035145,9347.0,7.0,...,21.0,13.0,9.0,1.0,7.0,15.0,0.0,2.0,47.0,0.0
4,31.0,21.0,3.0,Investment,8.993640e+06,89971.0,0.066941,0.306977,4993.0,4.0,...,205.0,88.0,19.0,2.0,63.0,100.0,0.0,28.0,132.0,14.0

Applying onehot encoding to convert classes into continuous value

In [28]:
Xt = pd.get_dummies(dfXt)
print(Xt.shape)
Xt.head()

(77789, 287)

,full_sq,life_sq,floor,area_m,raion_popul,green_zone_part,indust_part,children_preschool,preschool_education_centers_raion,children_school,...,water_1line_yes,big_road1_1line_no,big_road1_1line_yes,railroad_1line_no,railroad_1line_yes,ecology_excellent,ecology_good,ecology_no data,ecology_poor,ecology_satisfactory
0,89.0,50.0,9.0,1.258354e+07,178473.0,0.194703,0.069753,13087.0,9.0,13670.0,...,0,1,0,1,0,0,1,0,0,0
1,25.0,14.0,10.0,1.032047e+07,57405.0,0.523439,0.042307,2459.0,5.0,2810.0,...,0,1,0,1,0,0,0,0,1,0
2,38.0,19.0,11.0,7.632940e+06,78810.0,0.051844,0.437885,5519.0,3.0,5735.0,...,0,1,0,1,0,0,0,0,0,1
3,43.0,28.0,4.0,5.235177e+07,142462.0,0.070662,0.035145,9347.0,7.0,9292.0,...,0,1,0,1,0,0,0,0,0,1
4,31.0,21.0,3.0,8.993640e+06,89971.0,0.066941,0.306977,4993.0,4.0,5148.0,...,0,1,0,1,0,0,0,0,1,0

In [29]:
Xt.shape

(77789, 287)

# Correlation Matrix

In [30]:
cor=df.corr()

# Filtering

a) Remoeving features on self-corelation
b) Removing features on correlation with target variable
c) Removing features on Self variance

In [35]:
#  Removing of self correlation

# This  function will find correlation feateures with each other and tell feaure with are highly correlataed nearly same which can be removed

def self_corr(cormatrix,low_range,high_range):

    cor=cormatrix


    fcr_df=pd.DataFrame(columns= ['feature 1', 'feature 2', 'correlation values'])
    l=len(cor)
    fcor_rem=[]
    l
    for j in range(l):
        for k in range(l):
            fcor=cor.iloc[j-1,k-1]

            if fcor>=low_range and fcor <high_range:

                
                f2=cor.index[j-1]
                f3=cor.columns[k-1]

                
                fcor_rem.append([f2, f3, fcor])
                fcr_df=fcr_df.append({'feature 1': f2, 'feature 2' : f3, 'correlation values': fcor}, ignore_index=True)
                


    fcr12=fcr_df.copy()

    for i in range(len(fcr12)):
        for j in range(len(fcr12)):
            try:

                if fcr12.iloc[j,0]==fcr12.iloc[i,1]:
                    fcr12=fcr12.drop(j)
            except:
                    

             fcr12 =fcr12.reset_index(drop=True)

    print(fcr_df.head())
    return(fcr12['feature 1'])

In [36]:
rem_selfcor =self_corr(cor,0.8,1)

           feature 1                   feature 2  correlation values
0  office_count_5000             cafe_count_5000            0.816991
1  office_count_5000    cafe_count_5000_na_price            0.811909
2  office_count_5000   cafe_count_5000_price_500            0.815336
3  office_count_5000  cafe_count_5000_price_1000            0.816065
4  office_count_5000  cafe_count_5000_price_1500            0.812276

In [37]:
#  Removing of features on correlation with target variable

# if feature has very low correlation with target variable it can be neglected


def target_cor(cor_matrix,target_feature,lower_limit):

    cor= cor_matrix


    cor_target = abs(cor[target_feature])

    #Selecting highly correlated features
    relevant_features = cor_target[cor_target<lower_limit]
    print(relevant_features)
    return(relevant_features.index)

In [38]:
rem_cor=target_cor(cor,'price_doc',0.4)

raion_popul                          0.255183
green_zone_part                      0.268517
indust_part                          0.253134
children_preschool                   0.368395
preschool_education_centers_raion    0.290759
                                       ...
cafe_sum_5000_max_price_avg          0.359831
cafe_avg_price_5000                  0.366213
mosque_count_5000                    0.270513
sport_count_5000                     0.300094
market_count_5000                    0.236708
Name: price_doc, Length: 79, dtype: float64

In [39]:
rem_cor

Index(['raion_popul', 'green_zone_part', 'indust_part', 'children_preschool',
       'preschool_education_centers_raion', 'children_school',
       'school_education_centers_raion', 'healthcare_centers_raion',
       'sport_objects_raion', 'young_all', 'young_male', 'young_female',
       'work_all', 'work_male', 'work_female', 'ekder_all', 'ekder_male',
       'ekder_female', '0_6_all', '0_6_male', '0_6_female', '7_14_all',
       '7_14_male', '7_14_female', '0_17_all', '0_17_male', '0_17_female',
       '0_13_all', '0_13_male', '0_13_female', 'build_count_block',
       'build_count_panel', 'build_count_1971-1995', 'ID_metro',
       'water_treatment_km', 'incineration_km', 'railroad_station_walk_km',
       'railroad_station_walk_min', 'ID_railroad_station_walk',
       'railroad_station_avto_km', 'ID_railroad_station_avto', 'water_km',
       'ttk_km', 'sadovoe_km', 'bulvar_ring_km', 'kremlin_km', 'big_road1_km',
       'ID_big_road1', 'big_road2_km', 'ID_big_road2', 'zd_vokzaly_avto_km',
       'ID_railroad_terminal', 'ID_bus_terminal', 'oil_chemistry_km',
       'nuclear_reactor_km', 'big_market_km', 'detention_facility_km',
       'mosque_km', 'green_part_1500', 'prom_part_1500', 'green_part_2000',
       'prom_part_2000', 'green_part_3000', 'prom_part_3000',
       'cafe_sum_3000_min_price_avg', 'cafe_sum_3000_max_price_avg',
       'cafe_avg_price_3000', 'sport_count_3000', 'market_count_3000',
       'green_part_5000', 'prom_part_5000', 'trc_count_5000', 'trc_sqm_5000',
       'cafe_sum_5000_min_price_avg', 'cafe_sum_5000_max_price_avg',
       'cafe_avg_price_5000', 'mosque_count_5000', 'sport_count_5000',
       'market_count_5000'],
      dtype='object')

In [40]:
## Removing features with low self variance

## Features whcih remain constant can have no effect on predicting targert feature and can be removed

def self_var(dataset,limit):

    var=dataset.var()
    var_rem= var[var<limit]
    print(var_rem)
    return(var_rem.index)

In [41]:
rem_var=self_var(X,0.1)

green_zone_part              0.045573
indust_part                  0.019900
mosque_count_500             0.047256
mosque_count_1000            0.056570
mosque_count_1500            0.071232
mosque_count_2000            0.096186
incineration_raion_no        0.088340
incineration_raion_yes       0.088340
oil_chemistry_raion_no       0.079872
oil_chemistry_raion_yes      0.079872
nuclear_reactor_raion_no     0.093696
nuclear_reactor_raion_yes    0.093696
big_road1_1line_no           0.099714
big_road1_1line_yes          0.099714
railroad_1line_no            0.096000
railroad_1line_yes           0.096000
dtype: float64

In [42]:
rem_var

Index(['green_zone_part', 'indust_part', 'mosque_count_500',
       'mosque_count_1000', 'mosque_count_1500', 'mosque_count_2000',
       'incineration_raion_no', 'incineration_raion_yes',
       'oil_chemistry_raion_no', 'oil_chemistry_raion_yes',
       'nuclear_reactor_raion_no', 'nuclear_reactor_raion_yes',
       'big_road1_1line_no', 'big_road1_1line_yes', 'railroad_1line_no',
       'railroad_1line_yes'],
      dtype='object')

## Removing features

In [43]:
def remove_features(dataset,rem_feature):

    for i in rem_feature:
        try:
            dataset=dataset.drop(columns= i)
            dataset=dataset.reset_index(drop=True)

            print(dataset.shape)

        except:
            print('Missing')

    return(dataset)

In [44]:
rem_cor

Index(['raion_popul', 'green_zone_part', 'indust_part', 'children_preschool',
       'preschool_education_centers_raion', 'children_school',
       'school_education_centers_raion', 'healthcare_centers_raion',
       'sport_objects_raion', 'young_all', 'young_male', 'young_female',
       'work_all', 'work_male', 'work_female', 'ekder_all', 'ekder_male',
       'ekder_female', '0_6_all', '0_6_male', '0_6_female', '7_14_all',
       '7_14_male', '7_14_female', '0_17_all', '0_17_male', '0_17_female',
       '0_13_all', '0_13_male', '0_13_female', 'build_count_block',
       'build_count_panel', 'build_count_1971-1995', 'ID_metro',
       'water_treatment_km', 'incineration_km', 'railroad_station_walk_km',
       'railroad_station_walk_min', 'ID_railroad_station_walk',
       'railroad_station_avto_km', 'ID_railroad_station_avto', 'water_km',
       'ttk_km', 'sadovoe_km', 'bulvar_ring_km', 'kremlin_km', 'big_road1_km',
       'ID_big_road1', 'big_road2_km', 'ID_big_road2', 'zd_vokzaly_avto_km',
       'ID_railroad_terminal', 'ID_bus_terminal', 'oil_chemistry_km',
       'nuclear_reactor_km', 'big_market_km', 'detention_facility_km',
       'mosque_km', 'green_part_1500', 'prom_part_1500', 'green_part_2000',
       'prom_part_2000', 'green_part_3000', 'prom_part_3000',
       'cafe_sum_3000_min_price_avg', 'cafe_sum_3000_max_price_avg',
       'cafe_avg_price_3000', 'sport_count_3000', 'market_count_3000',
       'green_part_5000', 'prom_part_5000', 'trc_count_5000', 'trc_sqm_5000',
       'cafe_sum_5000_min_price_avg', 'cafe_sum_5000_max_price_avg',
       'cafe_avg_price_5000', 'mosque_count_5000', 'sport_count_5000',
       'market_count_5000'],
      dtype='object')

In [45]:
Xr=remove_features(X,rem_var)

(181507, 286)
(181507, 285)
(181507, 284)
(181507, 283)
(181507, 282)
(181507, 281)
(181507, 280)
(181507, 279)
(181507, 278)
(181507, 277)
(181507, 276)
(181507, 275)
(181507, 274)
(181507, 273)
(181507, 272)
(181507, 271)

In [46]:
Xr.shape

(181507, 271)

In [47]:
X.shape

(181507, 287)

# Removing features on P value

In [48]:
# This will remove features based on higher p-values

def p_val(dataset):

    p= len(dataset.columns)
    n= len(dataset.index)

    print(dataset.shape)
    Xsm=dataset.copy()
    Xsm = sm.add_constant(dataset)
    print(dataset.shape)
    mod = sm.OLS(y, Xsm)
    res = mod.fit()
    # # print(res.summary())

    ar=pd.DataFrame(columns = ['Features', 'P_Values'])
    c=[]
    for l in Xsm.columns:
        b = res.pvalues[l]
        if b > 0.05:

            ar= ar.append({'Features': l, 'P_Values': b},ignore_index=True)
            c.append(l)
            print(l,':',b)
    print(c)
    # ar.head(30)

    return(c)

In [49]:
rem_p=p_val(X)

(181507, 287)
(181507, 287)
area_m : 0.48714782552338587
indust_part : 0.7380758309531251
school_education_centers_raion : 0.15144324123398153
sport_objects_raion : 0.08615826192782934
culture_objects_top_25_raion : 0.9533386797348384
full_all : 0.9737798695484825
young_all : 0.5105806323639629
young_male : 0.4160941168152975
work_all : 0.3666113017495538
ekder_all : 0.09255879403431207
0_6_all : 0.9998129717828271
0_6_male : 0.4328441569562722
7_14_all : 0.6813597176856977
7_14_male : 0.9331362843786709
7_14_female : 0.11001012209248583
0_17_all : 0.06024453118050101
0_17_male : 0.10615346546283144
0_17_female : 0.07204361407344656
0_13_all : 0.31338871139254326
build_count_wood : 0.06341198253023397
build_count_brick : 0.9453976742955933
build_count_slag : 0.09493977465287191
build_count_before_1920 : 0.5692917770384965
build_count_1921-1945 : 0.4126588036810207
build_count_1946-1970 : 0.4256408304194119
metro_min_avto : 0.22802931634411155
metro_km_walk : 0.4956238270785309
incineration_km : 0.08843689257601363
railroad_station_walk_km : 0.27745564805215983
public_transport_station_km : 0.06122923466615889
bulvar_ring_km : 0.4191436863527582
big_road1_km : 0.8764802728255954
ID_big_road2 : 0.057771199276821006
railroad_km : 0.18634526150768257
bus_terminal_avto_km : 0.05573445789300863
radiation_km : 0.37454174052184697
power_transmission_line_km : 0.792228793800705
ts_km : 0.23202219818717618
market_shop_km : 0.9215908500376583
ice_rink_km : 0.10495481550063021
stadium_km : 0.08614345927089678
detention_facility_km : 0.0895587374694882
public_healthcare_km : 0.9289501656045236
preschool_km : 0.36156455185664793
big_church_km : 0.23036975496423676
mosque_km : 0.5940603330240994
exhibition_km : 0.8931850510090265
trc_count_500 : 0.3785529912018182
cafe_count_500_na_price : 0.12209811504008035
cafe_count_500_price_500 : 0.13839996857998352
cafe_count_500_price_2500 : 0.0824504457640709
church_count_500 : 0.08418971735495988
cafe_count_1000 : 0.8236065525856539
cafe_count_1000_price_500 : 0.050384875272601375
cafe_count_1000_price_2500 : 0.1637412685630929
cafe_count_1000_price_4000 : 0.832955508017915
sport_count_1000 : 0.3761305090604309
prom_part_1500 : 0.10493345366983528
office_count_1500 : 0.6859047833560314
trc_sqm_1500 : 0.6641752371479821
cafe_count_1500_price_500 : 0.5754336877352937
cafe_count_1500_price_1000 : 0.6610446535760917
cafe_count_1500_price_1500 : 0.2481221559770218
cafe_count_1500_price_high : 0.08836757526111973
big_church_count_1500 : 0.14770844425393506
sport_count_1500 : 0.1584082048649505
prom_part_2000 : 0.8222238666913587
trc_count_2000 : 0.39758951583541713
cafe_sum_2000_min_price_avg : 0.7488477737934218
cafe_avg_price_2000 : 0.11984174300231139
cafe_count_2000_na_price : 0.617539003775877
cafe_count_2000_price_500 : 0.3256306631906569
cafe_count_2000_price_2500 : 0.13542447603555083
church_count_2000 : 0.9232987925346003
leisure_count_2000 : 0.21182499933976054
market_count_2000 : 0.12504946187777508
green_part_3000 : 0.26157235386981065
office_sqm_3000 : 0.22672445960826587
trc_sqm_3000 : 0.18479667231433344
cafe_sum_3000_min_price_avg : 0.2594552092713303
cafe_count_3000_price_high : 0.8332914732111592
church_count_3000 : 0.6022601211339764
office_count_5000 : 0.25493808339904916
trc_count_5000 : 0.06809501850861926
cafe_sum_5000_min_price_avg : 0.21105857398781605
cafe_sum_5000_max_price_avg : 0.9288371382013071
cafe_count_5000_na_price : 0.5127801012598533
cafe_count_5000_price_500 : 0.23832752112437408
cafe_count_5000_price_1000 : 0.059194871412254726
cafe_count_5000_price_1500 : 0.5424375400597339
cafe_count_5000_price_2500 : 0.7274412777568346
cafe_count_5000_price_4000 : 0.804110439793716
cafe_count_5000_price_high : 0.6678927112458772
big_church_count_5000 : 0.5778101695488556
leisure_count_5000 : 0.37566980547156703
sport_count_5000 : 0.27289713920429765
thermal_power_plant_raion_no : 0.05482555495914076
thermal_power_plant_raion_yes : 0.15624664200882463
radiation_raion_yes : 0.2919183649512281
detention_facility_raion_yes : 0.7644351617970523
railroad_1line_no : 0.05254030496432491
ecology_poor : 0.26521249175507405
['area_m', 'indust_part', 'school_education_centers_raion', 'sport_objects_raion', 'culture_objects_top_25_raion', 'full_all', 'young_all', 'young_male', 'work_all', 'ekder_all', '0_6_all', '0_6_male', '7_14_all', '7_14_male', '7_14_female', '0_17_all', '0_17_male', '0_17_female', '0_13_all', 'build_count_wood', 'build_count_brick', 'build_count_slag', 'build_count_before_1920', 'build_count_1921-1945', 'build_count_1946-1970', 'metro_min_avto', 'metro_km_walk', 'incineration_km', 'railroad_station_walk_km', 'public_transport_station_km', 'bulvar_ring_km', 'big_road1_km', 'ID_big_road2', 'railroad_km', 'bus_terminal_avto_km', 'radiation_km', 'power_transmission_line_km', 'ts_km', 'market_shop_km', 'ice_rink_km', 'stadium_km', 'detention_facility_km', 'public_healthcare_km', 'preschool_km', 'big_church_km', 'mosque_km', 'exhibition_km', 'trc_count_500', 'cafe_count_500_na_price', 'cafe_count_500_price_500', 'cafe_count_500_price_2500', 'church_count_500', 'cafe_count_1000', 'cafe_count_1000_price_500', 'cafe_count_1000_price_2500', 'cafe_count_1000_price_4000', 'sport_count_1000', 'prom_part_1500', 'office_count_1500', 'trc_sqm_1500', 'cafe_count_1500_price_500', 'cafe_count_1500_price_1000', 'cafe_count_1500_price_1500', 'cafe_count_1500_price_high', 'big_church_count_1500', 'sport_count_1500', 'prom_part_2000', 'trc_count_2000', 'cafe_sum_2000_min_price_avg', 'cafe_avg_price_2000', 'cafe_count_2000_na_price', 'cafe_count_2000_price_500', 'cafe_count_2000_price_2500', 'church_count_2000', 'leisure_count_2000', 'market_count_2000', 'green_part_3000', 'office_sqm_3000', 'trc_sqm_3000', 'cafe_sum_3000_min_price_avg', 'cafe_count_3000_price_high', 'church_count_3000', 'office_count_5000', 'trc_count_5000', 'cafe_sum_5000_min_price_avg', 'cafe_sum_5000_max_price_avg', 'cafe_count_5000_na_price', 'cafe_count_5000_price_500', 'cafe_count_5000_price_1000', 'cafe_count_5000_price_1500', 'cafe_count_5000_price_2500', 'cafe_count_5000_price_4000', 'cafe_count_5000_price_high', 'big_church_count_5000', 'leisure_count_5000', 'sport_count_5000', 'thermal_power_plant_raion_no', 'thermal_power_plant_raion_yes', 'radiation_raion_yes', 'detention_facility_raion_yes', 'railroad_1line_no', 'ecology_poor']

In [50]:
X2=remove_features(X,rem_cor)

print(X2.shape)

(181507, 286)
(181507, 285)
(181507, 284)
(181507, 283)
(181507, 282)
(181507, 281)
(181507, 280)
(181507, 279)
(181507, 278)
(181507, 277)
(181507, 276)
(181507, 275)
(181507, 274)
(181507, 273)
(181507, 272)
(181507, 271)
(181507, 270)
(181507, 269)
(181507, 268)
(181507, 267)
(181507, 266)
(181507, 265)
(181507, 264)
(181507, 263)
(181507, 262)
(181507, 261)
(181507, 260)
(181507, 259)
(181507, 258)
(181507, 257)
(181507, 256)
(181507, 255)
(181507, 254)
(181507, 253)
(181507, 252)
(181507, 251)
(181507, 250)
(181507, 249)
(181507, 248)
(181507, 247)
(181507, 246)
(181507, 245)
(181507, 244)
(181507, 243)
(181507, 242)
(181507, 241)
(181507, 240)
(181507, 239)
(181507, 238)
(181507, 237)
(181507, 236)
(181507, 235)
(181507, 234)
(181507, 233)
(181507, 232)
(181507, 231)
(181507, 230)
(181507, 229)
(181507, 228)
(181507, 227)
(181507, 226)
(181507, 225)
(181507, 224)
(181507, 223)
(181507, 222)
(181507, 221)
(181507, 220)
(181507, 219)
(181507, 218)
(181507, 217)
(181507, 216)
(181507, 215)
(181507, 214)
(181507, 213)
(181507, 212)
(181507, 211)
(181507, 210)
(181507, 209)
(181507, 208)
(181507, 208)

In [51]:
X2=remove_features(X2,rem_selfcor)

print(X2.shape)

(181507, 207)
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
(181507, 206)
Missing
Missing
Missing
(181507, 205)
Missing
Missing
Missing
(181507, 204)
Missing
Missing
Missing
(181507, 203)
Missing
Missing
Missing
(181507, 202)
(181507, 201)
Missing
(181507, 200)
(181507, 200)

In [52]:
X2=remove_features(X2,rem_var)

print(X2.shape)

Missing
Missing
(181507, 199)
(181507, 198)
(181507, 197)
(181507, 196)
(181507, 195)
(181507, 194)
(181507, 193)
(181507, 192)
(181507, 191)
(181507, 190)
(181507, 189)
(181507, 188)
(181507, 187)
(181507, 186)
(181507, 186)

In [53]:
X2=remove_features(X2,rem_p)

print(X2.shape)

(181507, 185)
Missing
Missing
Missing
(181507, 184)
(181507, 183)
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
(181507, 182)
(181507, 181)
(181507, 180)
(181507, 179)
(181507, 178)
(181507, 177)
(181507, 176)
(181507, 175)
Missing
Missing
(181507, 174)
Missing
Missing
Missing
(181507, 173)
(181507, 172)
(181507, 171)
(181507, 170)
(181507, 169)
(181507, 168)
(181507, 167)
(181507, 166)
Missing
(181507, 165)
(181507, 164)
(181507, 163)
Missing
(181507, 162)
(181507, 161)
(181507, 160)
(181507, 159)
(181507, 158)
(181507, 157)
(181507, 156)
(181507, 155)
(181507, 154)
(181507, 153)
(181507, 152)
Missing
(181507, 151)
(181507, 150)
(181507, 149)
(181507, 148)
(181507, 147)
(181507, 146)
(181507, 145)
(181507, 144)
Missing
(181507, 143)
(181507, 142)
(181507, 141)
(181507, 140)
(181507, 139)
(181507, 138)
(181507, 137)
(181507, 136)
(181507, 135)
Missing
(181507, 134)
(181507, 133)
Missing
(181507, 132)
(181507, 131)
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
(181507, 130)
(181507, 129)
Missing
Missing
(181507, 128)
Missing
(181507, 127)
(181507, 126)
(181507, 125)
(181507, 124)
Missing
(181507, 123)
(181507, 123)

In [54]:
X2t=Xt.copy()
X2t=X2t[X2.columns]
X2t.shape

(77789, 123)

# Normalizing scaling data

In [55]:
def scaling(dataset):
    from sklearn.preprocessing import MinMaxScaler
    scaler = MinMaxScaler(feature_range=(0, 1))
    X2_Scaled = scaler.fit_transform(dataset)
    X2df_Scaled = pd.DataFrame(X2_Scaled)
    X2df_Scaled.columns = dataset.columns
    return(X2df_Scaled)

In [56]:
X2.head()

,full_sq,life_sq,floor,school_education_centers_top_20_raion,university_top_20_raion,additional_education_raion,shopping_centers_raion,office_raion,male_f,female_f,...,railroad_terminal_raion_yes,big_market_raion_no,big_market_raion_yes,detention_facility_raion_no,water_1line_no,water_1line_yes,ecology_excellent,ecology_good,ecology_no data,ecology_satisfactory
0,43.0,27.0,4.0,0.0,0.0,3.0,16.0,1.0,40477.0,45729.0,...,0,1,0,1,1,0,0,1,0,0
1,34.0,19.0,3.0,0.0,0.0,1.0,3.0,0.0,34200.0,42084.0,...,0,1,0,1,1,0,1,0,0,0
2,43.0,29.0,2.0,0.0,0.0,1.0,0.0,1.0,46076.0,55906.0,...,0,1,0,1,1,0,0,0,0,0
3,77.0,77.0,4.0,0.0,2.0,2.0,10.0,93.0,13522.0,14657.0,...,1,1,0,1,1,0,1,0,0,0
4,67.0,46.0,14.0,0.0,0.0,0.0,6.0,19.0,9400.0,10540.0,...,0,1,0,1,1,0,0,0,0,0

In [57]:
X2s= scaling(X2)
X2s.head()

,full_sq,life_sq,floor,school_education_centers_top_20_raion,university_top_20_raion,additional_education_raion,shopping_centers_raion,office_raion,male_f,female_f,...,railroad_terminal_raion_yes,big_market_raion_no,big_market_raion_yes,detention_facility_raion_no,water_1line_no,water_1line_yes,ecology_excellent,ecology_good,ecology_no data,ecology_satisfactory
0,0.008074,0.003611,0.051949,0.0,0.000000,0.1875,0.695652,0.007092,0.050776,0.047181,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.006384,0.002541,0.038962,0.0,0.000000,0.0625,0.130435,0.000000,0.042660,0.043307,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
2,0.008074,0.003878,0.025974,0.0,0.000000,0.0625,0.000000,0.007092,0.058016,0.057998,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.014457,0.010297,0.051949,0.0,0.666667,0.1250,0.434783,0.659574,0.015922,0.014154,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
4,0.012580,0.006151,0.181821,0.0,0.000000,0.0000,0.260870,0.134752,0.010593,0.009778,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0

In [45]:
X2ts=scaling(X2t)
X2ts.head()

,full_sq,life_sq,floor,school_education_centers_top_20_raion,university_top_20_raion,additional_education_raion,shopping_centers_raion,office_raion,16_29_male,16_29_female,...,sport_count_2000,trc_count_3000,cafe_count_3000_price_1500,cafe_count_3000_price_2500,cafe_count_3000_price_4000,big_church_count_3000,mosque_count_3000,leisure_count_3000,church_count_5000,radiation_raion_no
0,0.016709,0.006688,0.116883,0.0,0.000000,0.3750,0.478261,0.028369,0.006615,0.008172,...,0.240774,0.181818,0.022422,0.011279,0.000000,0.009804,0.0,0.000000,0.016003,1.0
1,0.004688,0.001873,0.129870,0.0,0.000000,0.3750,0.260870,0.063830,0.056629,0.046835,...,0.518589,0.363636,0.082960,0.060153,0.017701,0.166667,0.0,0.094118,0.320060,1.0
2,0.007130,0.002542,0.142857,0.0,0.000000,0.1250,0.217391,0.021277,0.049742,0.041590,...,0.129647,0.166667,0.026906,0.007519,0.000000,0.039216,0.0,0.000000,0.036007,0.0
3,0.008069,0.003745,0.051948,0.0,0.000000,0.1250,0.130435,0.021277,0.047686,0.036694,...,0.166689,0.227273,0.026906,0.011279,0.017701,0.049020,0.0,0.023529,0.060011,0.0
4,0.005815,0.002809,0.038961,0.0,0.333333,0.0625,0.304348,0.099291,0.069713,0.067540,...,0.314858,0.363636,0.087444,0.037596,0.000000,0.176471,0.0,0.047059,0.400075,0.0

In [46]:
X2t.head()

,full_sq,life_sq,floor,school_education_centers_top_20_raion,university_top_20_raion,additional_education_raion,shopping_centers_raion,office_raion,16_29_male,16_29_female,...,sport_count_2000,trc_count_3000,cafe_count_3000_price_1500,cafe_count_3000_price_2500,cafe_count_3000_price_4000,big_church_count_3000,mosque_count_3000,leisure_count_3000,church_count_5000,radiation_raion_no
0,89.0,50.0,9.0,0.0,0.0,6.0,11.0,4.0,1450.0,1842.0,...,13.0,12.0,10.0,3.0,0.0,1.0,0.0,0.0,4.0,1
1,25.0,14.0,10.0,0.0,0.0,6.0,6.0,9.0,10085.0,9360.0,...,28.0,24.0,37.0,16.0,2.0,17.0,0.0,8.0,80.0,1
2,38.0,19.0,11.0,0.0,0.0,2.0,5.0,3.0,8896.0,8340.0,...,7.0,11.0,12.0,2.0,0.0,4.0,0.0,0.0,9.0,0
3,43.0,28.0,4.0,0.0,0.0,2.0,3.0,3.0,8541.0,7388.0,...,9.0,15.0,12.0,3.0,2.0,5.0,0.0,2.0,15.0,0
4,31.0,21.0,3.0,0.0,1.0,1.0,7.0,14.0,12344.0,13386.0,...,17.0,24.0,39.0,10.0,0.0,18.0,0.0,4.0,100.0,0

In [47]:
X2ts.shape

(77789, 85)

In [52]:
neigh = KNeighborsRegressor(n_neighbors=3)
#X2s = df[['TV','radio']]
#y = df[['sales']]
knn_reg = neigh.fit(X2, y)
print(knn_reg.score(X2, y))
# print(reg.coef_)
# print(reg.intercept_)
print(X2ts.shape)
y_pred = knn_reg.predict(X2)
print("Mean squared error: %.2f" % mean_squared_error(y, y_pred))
print("Coefficient of determination: %.3f" % r2_score(y, y_pred))

y_pred_test_df = knn_reg.predict(X2t)

Xt=pd.read_csv('test.csv')
ro=Xt['row ID']
type(ro)
row=ro.values

prd=pd.DataFrame({'row ID' : row, 'price_doc': y_pred_test_df}, index=None)

prd
prd.head()

prd.to_csv('output34.csv',index=False)

0.7738901967879019
(77789, 85)
Mean squared error: 107782154860237.08
Coefficient of determination: 0.774

In [58]:


def LR(X_train,X_test):

    p= len(X_train.columns)
    print(p)
    n= len(X_train.index)
    print(n)

    reg = LinearRegression().fit(X_train, y)
    print(reg.score(X_train, y))
    print(reg.coef_)
    print(reg.intercept_)

    y_pred = reg.predict(X_train)

    print("Mean squared error: %.2f" % mean_squared_error(y, y_pred))
    print("R2: %.2f" % r2_score(y, y_pred))


    mse = mean_squared_error(y, y_pred)
    r2= r2_score(y, y_pred)
    Adj_r2 = 1-(1-r2)*((n-1)/(n-p-1))
    print(Adj_r2)

    y_pred_test = reg.predict(X_test)

    return(y_pred_test)

In [59]:
def result_y(ypred,result_filename):
    ro=df_test['row ID']
    type(ro)
    row=ro.values

    prd=pd.DataFrame({'row ID' : row, 'price_doc': ypred}, index=None)

    prd
    prd.head()

    prd.to_csv(result_filename,index=False)

In [67]:
# X2t=X2t[[X2.columns]]

In [68]:
Xt.shape

(77789, 272)

In [50]:


rem_selfcor =self_corr(cor,0.8,1)

rem_cor=target_cor(cor,'price_doc',0.3)

rem_var=self_var(X,0.1)

rem_p=p_val(X)

X2=remove_features(X,rem_cor)

X2=remove_features(X2,rem_selfcor)

X2=remove_features(X2,rem_var)

X2=remove_features(X2,rem_p)

X2t=Xt[X2.columns]

# op=LR(X2,X2t)

# ydf=(op,'output35')

(181507, 287)
(181507, 287)
area_m : 0.48714782552338587
indust_part : 0.7380758309531251
school_education_centers_raion : 0.15144324123398153
sport_objects_raion : 0.08615826192782934
culture_objects_top_25_raion : 0.9533386797348384
full_all : 0.9737798695484825
young_all : 0.5105806323639629
young_male : 0.4160941168152975
work_all : 0.3666113017495538
ekder_all : 0.09255879403431207
0_6_all : 0.9998129717828271
0_6_male : 0.4328441569562722
7_14_all : 0.6813597176856977
7_14_male : 0.9331362843786709
7_14_female : 0.11001012209248583
0_17_all : 0.06024453118050101
0_17_male : 0.10615346546283144
0_17_female : 0.07204361407344656
0_13_all : 0.31338871139254326
build_count_wood : 0.06341198253023397
build_count_brick : 0.9453976742955933
build_count_slag : 0.09493977465287191
build_count_before_1920 : 0.5692917770384965
build_count_1921-1945 : 0.4126588036810207
build_count_1946-1970 : 0.4256408304194119
metro_min_avto : 0.22802931634411155
metro_km_walk : 0.4956238270785309
incineration_km : 0.08843689257601363
railroad_station_walk_km : 0.27745564805215983
public_transport_station_km : 0.06122923466615889
bulvar_ring_km : 0.4191436863527582
big_road1_km : 0.8764802728255954
ID_big_road2 : 0.057771199276821006
railroad_km : 0.18634526150768257
bus_terminal_avto_km : 0.05573445789300863
radiation_km : 0.37454174052184697
power_transmission_line_km : 0.792228793800705
ts_km : 0.23202219818717618
market_shop_km : 0.9215908500376583
ice_rink_km : 0.10495481550063021
stadium_km : 0.08614345927089678
detention_facility_km : 0.0895587374694882
public_healthcare_km : 0.9289501656045236
preschool_km : 0.36156455185664793
big_church_km : 0.23036975496423676
mosque_km : 0.5940603330240994
exhibition_km : 0.8931850510090265
trc_count_500 : 0.3785529912018182
cafe_count_500_na_price : 0.12209811504008035
cafe_count_500_price_500 : 0.13839996857998352
cafe_count_500_price_2500 : 0.0824504457640709
church_count_500 : 0.08418971735495988
cafe_count_1000 : 0.8236065525856539
cafe_count_1000_price_500 : 0.050384875272601375
cafe_count_1000_price_2500 : 0.1637412685630929
cafe_count_1000_price_4000 : 0.832955508017915
sport_count_1000 : 0.3761305090604309
prom_part_1500 : 0.10493345366983528
office_count_1500 : 0.6859047833560314
trc_sqm_1500 : 0.6641752371479821
cafe_count_1500_price_500 : 0.5754336877352937
cafe_count_1500_price_1000 : 0.6610446535760917
cafe_count_1500_price_1500 : 0.2481221559770218
cafe_count_1500_price_high : 0.08836757526111973
big_church_count_1500 : 0.14770844425393506
sport_count_1500 : 0.1584082048649505
prom_part_2000 : 0.8222238666913587
trc_count_2000 : 0.39758951583541713
cafe_sum_2000_min_price_avg : 0.7488477737934218
cafe_avg_price_2000 : 0.11984174300231139
cafe_count_2000_na_price : 0.617539003775877
cafe_count_2000_price_500 : 0.3256306631906569
cafe_count_2000_price_2500 : 0.13542447603555083
church_count_2000 : 0.9232987925346003
leisure_count_2000 : 0.21182499933976054
market_count_2000 : 0.12504946187777508
green_part_3000 : 0.26157235386981065
office_sqm_3000 : 0.22672445960826587
trc_sqm_3000 : 0.18479667231433344
cafe_sum_3000_min_price_avg : 0.2594552092713303
cafe_count_3000_price_high : 0.8332914732111592
church_count_3000 : 0.6022601211339764
office_count_5000 : 0.25493808339904916
trc_count_5000 : 0.06809501850861926
cafe_sum_5000_min_price_avg : 0.21105857398781605
cafe_sum_5000_max_price_avg : 0.9288371382013071
cafe_count_5000_na_price : 0.5127801012598533
cafe_count_5000_price_500 : 0.23832752112437408
cafe_count_5000_price_1000 : 0.059194871412254726
cafe_count_5000_price_1500 : 0.5424375400597339
cafe_count_5000_price_2500 : 0.7274412777568346
cafe_count_5000_price_4000 : 0.804110439793716
cafe_count_5000_price_high : 0.6678927112458772
big_church_count_5000 : 0.5778101695488556
leisure_count_5000 : 0.37566980547156703
sport_count_5000 : 0.27289713920429765
thermal_power_plant_raion_no : 0.05482555495914076
thermal_power_plant_raion_yes : 0.15624664200882463
radiation_raion_yes : 0.2919183649512281
detention_facility_raion_yes : 0.7644351617970523
railroad_1line_no : 0.05254030496432491
ecology_poor : 0.26521249175507405
['area_m', 'indust_part', 'school_education_centers_raion', 'sport_objects_raion', 'culture_objects_top_25_raion', 'full_all', 'young_all', 'young_male', 'work_all', 'ekder_all', '0_6_all', '0_6_male', '7_14_all', '7_14_male', '7_14_female', '0_17_all', '0_17_male', '0_17_female', '0_13_all', 'build_count_wood', 'build_count_brick', 'build_count_slag', 'build_count_before_1920', 'build_count_1921-1945', 'build_count_1946-1970', 'metro_min_avto', 'metro_km_walk', 'incineration_km', 'railroad_station_walk_km', 'public_transport_station_km', 'bulvar_ring_km', 'big_road1_km', 'ID_big_road2', 'railroad_km', 'bus_terminal_avto_km', 'radiation_km', 'power_transmission_line_km', 'ts_km', 'market_shop_km', 'ice_rink_km', 'stadium_km', 'detention_facility_km', 'public_healthcare_km', 'preschool_km', 'big_church_km', 'mosque_km', 'exhibition_km', 'trc_count_500', 'cafe_count_500_na_price', 'cafe_count_500_price_500', 'cafe_count_500_price_2500', 'church_count_500', 'cafe_count_1000', 'cafe_count_1000_price_500', 'cafe_count_1000_price_2500', 'cafe_count_1000_price_4000', 'sport_count_1000', 'prom_part_1500', 'office_count_1500', 'trc_sqm_1500', 'cafe_count_1500_price_500', 'cafe_count_1500_price_1000', 'cafe_count_1500_price_1500', 'cafe_count_1500_price_high', 'big_church_count_1500', 'sport_count_1500', 'prom_part_2000', 'trc_count_2000', 'cafe_sum_2000_min_price_avg', 'cafe_avg_price_2000', 'cafe_count_2000_na_price', 'cafe_count_2000_price_500', 'cafe_count_2000_price_2500', 'church_count_2000', 'leisure_count_2000', 'market_count_2000', 'green_part_3000', 'office_sqm_3000', 'trc_sqm_3000', 'cafe_sum_3000_min_price_avg', 'cafe_count_3000_price_high', 'church_count_3000', 'office_count_5000', 'trc_count_5000', 'cafe_sum_5000_min_price_avg', 'cafe_sum_5000_max_price_avg', 'cafe_count_5000_na_price', 'cafe_count_5000_price_500', 'cafe_count_5000_price_1000', 'cafe_count_5000_price_1500', 'cafe_count_5000_price_2500', 'cafe_count_5000_price_4000', 'cafe_count_5000_price_high', 'big_church_count_5000', 'leisure_count_5000', 'sport_count_5000', 'thermal_power_plant_raion_no', 'thermal_power_plant_raion_yes', 'radiation_raion_yes', 'detention_facility_raion_yes', 'railroad_1line_no', 'ecology_poor']
(181507, 286)
(181507, 285)
(181507, 284)
(181507, 283)
(181507, 282)
(181507, 281)
(181507, 280)
(181507, 279)
(181507, 278)
(181507, 277)
(181507, 276)
(181507, 275)
(181507, 274)
(181507, 273)
(181507, 272)
(181507, 271)
(181507, 270)
(181507, 269)
(181507, 268)
(181507, 267)
(181507, 266)
(181507, 265)
(181507, 264)
(181507, 263)
(181507, 262)
(181507, 261)
(181507, 260)
(181507, 259)
(181507, 258)
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
(181507, 257)
Missing
Missing
Missing
(181507, 256)
Missing
Missing
Missing
(181507, 255)
Missing
Missing
Missing
(181507, 254)
Missing
Missing
Missing
(181507, 253)
(181507, 252)
Missing
(181507, 251)
Missing
Missing
(181507, 250)
(181507, 249)
(181507, 248)
(181507, 247)
(181507, 246)
(181507, 245)
(181507, 244)
(181507, 243)
(181507, 242)
(181507, 241)
(181507, 240)
(181507, 239)
(181507, 238)
(181507, 237)
(181507, 236)
Missing
Missing
(181507, 235)
(181507, 234)
(181507, 233)
(181507, 232)
(181507, 231)
Missing
Missing
(181507, 230)
(181507, 229)
(181507, 228)
(181507, 227)
(181507, 226)
(181507, 225)
(181507, 224)
(181507, 223)
(181507, 222)
(181507, 221)
(181507, 220)
(181507, 219)
(181507, 218)
(181507, 217)
(181507, 216)
(181507, 215)
(181507, 214)
(181507, 213)
(181507, 212)
(181507, 211)
(181507, 210)
(181507, 209)
Missing
(181507, 208)
(181507, 207)
(181507, 206)
(181507, 205)
(181507, 204)
(181507, 203)
(181507, 202)
(181507, 201)
(181507, 200)
(181507, 199)
(181507, 198)
(181507, 197)
(181507, 196)
(181507, 195)
(181507, 194)
(181507, 193)
(181507, 192)
(181507, 191)
(181507, 190)
(181507, 189)
(181507, 188)
(181507, 187)
(181507, 186)
(181507, 185)
(181507, 184)
(181507, 183)
(181507, 182)
(181507, 181)
(181507, 180)
(181507, 179)
(181507, 178)
(181507, 177)
(181507, 176)
(181507, 175)
(181507, 174)
(181507, 173)
(181507, 172)
(181507, 171)
(181507, 170)
(181507, 169)
(181507, 168)
(181507, 167)
(181507, 166)
Missing
(181507, 165)
(181507, 164)
(181507, 163)
(181507, 162)
(181507, 161)
Missing
(181507, 160)
(181507, 159)
(181507, 158)
Missing
Missing
Missing
Missing
(181507, 157)
(181507, 156)
Missing
Missing
(181507, 155)
(181507, 154)
(181507, 153)
(181507, 152)
(181507, 151)
(181507, 150)
Missing
(181507, 149)

# Feature selection

In [61]:


def f_sel(dataset,number):

    ols_reg = LinearRegression()
    sfs = SequentialFeatureSelector(ols_reg, direction='forward',n_features_to_select=number)
    sfs.fit(dataset, y)
    features = list(sfs.get_feature_names_out())
    print(sfs.get_feature_names_out())
    sel=sfs.get_feature_names_out()
    X2_Red = dataset[features]
    scores = cross_val_score(reg, X2_Red, y, cv=cv) 
    print(mean(scores))
    return(sel)

In [98]:
f_15=f_sel(X2,15)

['full_sq' 'life_sq' 'floor' 'build_count_monolith' 'industrial_km'
 'prom_part_500' 'trc_sqm_500' 'cafe_count_500_price_high'
 'leisure_count_500' 'green_part_1000' 'office_sqm_1000'
 'cafe_count_1000_price_high' 'leisure_count_1000' 'market_count_1000'
 'sport_count_2000']
0.6097959227570017

In [99]:
f_20=f_sel(X2,20)

['full_sq' 'life_sq' 'floor' 'school_education_centers_top_20_raion'
 'male_f' 'build_count_monolith' 'green_zone_km' 'industrial_km'
 'church_synagogue_km' 'prom_part_500' 'trc_sqm_500'
 'cafe_count_500_price_high' 'leisure_count_500' 'green_part_1000'
 'office_sqm_1000' 'cafe_count_1000_price_high' 'leisure_count_1000'
 'market_count_1000' 'trc_sqm_2000' 'sport_count_2000']
0.6139179922467107

In [101]:
X20=X2[f_20]

In [102]:
X20.shape

(181507, 20)

# Polynominal

In [62]:
def poly_df(dataset):
    
    poly = PolynomialFeatures(2)
    X2p = poly.fit_transform(dataset)
    X2pdf = pd.DataFrame(X2p)
    X2pdf.columns = list(poly.get_feature_names_out())
    scores = cross_val_score(reg, X2pdf, y, cv=cv)
    print(poly.get_feature_names_out()) 
    print(mean(scores))
    return(X2pdf)

In [63]:
def polyt_df(dataset):
    
    poly = PolynomialFeatures(2)
    X2p = poly.fit_transform(dataset)
    X2pdf = pd.DataFrame(X2p)
    X2pdf.columns = list(poly.get_feature_names_out())
    print(poly.get_feature_names_out()) 
    return(X2pdf)

In [104]:
X20p = poly_df(X20)

['1' 'full_sq' 'life_sq' 'floor' 'school_education_centers_top_20_raion'
 'male_f' 'build_count_monolith' 'green_zone_km' 'industrial_km'
 'church_synagogue_km' 'prom_part_500' 'trc_sqm_500'
 'cafe_count_500_price_high' 'leisure_count_500' 'green_part_1000'
 'office_sqm_1000' 'cafe_count_1000_price_high' 'leisure_count_1000'
 'market_count_1000' 'trc_sqm_2000' 'sport_count_2000' 'full_sq^2'
 'full_sq life_sq' 'full_sq floor'
 'full_sq school_education_centers_top_20_raion' 'full_sq male_f'
 'full_sq build_count_monolith' 'full_sq green_zone_km'
 'full_sq industrial_km' 'full_sq church_synagogue_km'
 'full_sq prom_part_500' 'full_sq trc_sqm_500'
 'full_sq cafe_count_500_price_high' 'full_sq leisure_count_500'
 'full_sq green_part_1000' 'full_sq office_sqm_1000'
 'full_sq cafe_count_1000_price_high' 'full_sq leisure_count_1000'
 'full_sq market_count_1000' 'full_sq trc_sqm_2000'
 'full_sq sport_count_2000' 'life_sq^2' 'life_sq floor'
 'life_sq school_education_centers_top_20_raion' 'life_sq male_f'
 'life_sq build_count_monolith' 'life_sq green_zone_km'
 'life_sq industrial_km' 'life_sq church_synagogue_km'
 'life_sq prom_part_500' 'life_sq trc_sqm_500'
 'life_sq cafe_count_500_price_high' 'life_sq leisure_count_500'
 'life_sq green_part_1000' 'life_sq office_sqm_1000'
 'life_sq cafe_count_1000_price_high' 'life_sq leisure_count_1000'
 'life_sq market_count_1000' 'life_sq trc_sqm_2000'
 'life_sq sport_count_2000' 'floor^2'
 'floor school_education_centers_top_20_raion' 'floor male_f'
 'floor build_count_monolith' 'floor green_zone_km' 'floor industrial_km'
 'floor church_synagogue_km' 'floor prom_part_500' 'floor trc_sqm_500'
 'floor cafe_count_500_price_high' 'floor leisure_count_500'
 'floor green_part_1000' 'floor office_sqm_1000'
 'floor cafe_count_1000_price_high' 'floor leisure_count_1000'
 'floor market_count_1000' 'floor trc_sqm_2000' 'floor sport_count_2000'
 'school_education_centers_top_20_raion^2'
 'school_education_centers_top_20_raion male_f'
 'school_education_centers_top_20_raion build_count_monolith'
 'school_education_centers_top_20_raion green_zone_km'
 'school_education_centers_top_20_raion industrial_km'
 'school_education_centers_top_20_raion church_synagogue_km'
 'school_education_centers_top_20_raion prom_part_500'
 'school_education_centers_top_20_raion trc_sqm_500'
 'school_education_centers_top_20_raion cafe_count_500_price_high'
 'school_education_centers_top_20_raion leisure_count_500'
 'school_education_centers_top_20_raion green_part_1000'
 'school_education_centers_top_20_raion office_sqm_1000'
 'school_education_centers_top_20_raion cafe_count_1000_price_high'
 'school_education_centers_top_20_raion leisure_count_1000'
 'school_education_centers_top_20_raion market_count_1000'
 'school_education_centers_top_20_raion trc_sqm_2000'
 'school_education_centers_top_20_raion sport_count_2000' 'male_f^2'
 'male_f build_count_monolith' 'male_f green_zone_km'
 'male_f industrial_km' 'male_f church_synagogue_km'
 'male_f prom_part_500' 'male_f trc_sqm_500'
 'male_f cafe_count_500_price_high' 'male_f leisure_count_500'
 'male_f green_part_1000' 'male_f office_sqm_1000'
 'male_f cafe_count_1000_price_high' 'male_f leisure_count_1000'
 'male_f market_count_1000' 'male_f trc_sqm_2000'
 'male_f sport_count_2000' 'build_count_monolith^2'
 'build_count_monolith green_zone_km' 'build_count_monolith industrial_km'
 'build_count_monolith church_synagogue_km'
 'build_count_monolith prom_part_500' 'build_count_monolith trc_sqm_500'
 'build_count_monolith cafe_count_500_price_high'
 'build_count_monolith leisure_count_500'
 'build_count_monolith green_part_1000'
 'build_count_monolith office_sqm_1000'
 'build_count_monolith cafe_count_1000_price_high'
 'build_count_monolith leisure_count_1000'
 'build_count_monolith market_count_1000'
 'build_count_monolith trc_sqm_2000'
 'build_count_monolith sport_count_2000' 'green_zone_km^2'
 'green_zone_km industrial_km' 'green_zone_km church_synagogue_km'
 'green_zone_km prom_part_500' 'green_zone_km trc_sqm_500'
 'green_zone_km cafe_count_500_price_high'
 'green_zone_km leisure_count_500' 'green_zone_km green_part_1000'
 'green_zone_km office_sqm_1000'
 'green_zone_km cafe_count_1000_price_high'
 'green_zone_km leisure_count_1000' 'green_zone_km market_count_1000'
 'green_zone_km trc_sqm_2000' 'green_zone_km sport_count_2000'
 'industrial_km^2' 'industrial_km church_synagogue_km'
 'industrial_km prom_part_500' 'industrial_km trc_sqm_500'
 'industrial_km cafe_count_500_price_high'
 'industrial_km leisure_count_500' 'industrial_km green_part_1000'
 'industrial_km office_sqm_1000'
 'industrial_km cafe_count_1000_price_high'
 'industrial_km leisure_count_1000' 'industrial_km market_count_1000'
 'industrial_km trc_sqm_2000' 'industrial_km sport_count_2000'
 'church_synagogue_km^2' 'church_synagogue_km prom_part_500'
 'church_synagogue_km trc_sqm_500'
 'church_synagogue_km cafe_count_500_price_high'
 'church_synagogue_km leisure_count_500'
 'church_synagogue_km green_part_1000'
 'church_synagogue_km office_sqm_1000'
 'church_synagogue_km cafe_count_1000_price_high'
 'church_synagogue_km leisure_count_1000'
 'church_synagogue_km market_count_1000'
 'church_synagogue_km trc_sqm_2000' 'church_synagogue_km sport_count_2000'
 'prom_part_500^2' 'prom_part_500 trc_sqm_500'
 'prom_part_500 cafe_count_500_price_high'
 'prom_part_500 leisure_count_500' 'prom_part_500 green_part_1000'
 'prom_part_500 office_sqm_1000'
 'prom_part_500 cafe_count_1000_price_high'
 'prom_part_500 leisure_count_1000' 'prom_part_500 market_count_1000'
 'prom_part_500 trc_sqm_2000' 'prom_part_500 sport_count_2000'
 'trc_sqm_500^2' 'trc_sqm_500 cafe_count_500_price_high'
 'trc_sqm_500 leisure_count_500' 'trc_sqm_500 green_part_1000'
 'trc_sqm_500 office_sqm_1000' 'trc_sqm_500 cafe_count_1000_price_high'
 'trc_sqm_500 leisure_count_1000' 'trc_sqm_500 market_count_1000'
 'trc_sqm_500 trc_sqm_2000' 'trc_sqm_500 sport_count_2000'
 'cafe_count_500_price_high^2'
 'cafe_count_500_price_high leisure_count_500'
 'cafe_count_500_price_high green_part_1000'
 'cafe_count_500_price_high office_sqm_1000'
 'cafe_count_500_price_high cafe_count_1000_price_high'
 'cafe_count_500_price_high leisure_count_1000'
 'cafe_count_500_price_high market_count_1000'
 'cafe_count_500_price_high trc_sqm_2000'
 'cafe_count_500_price_high sport_count_2000' 'leisure_count_500^2'
 'leisure_count_500 green_part_1000' 'leisure_count_500 office_sqm_1000'
 'leisure_count_500 cafe_count_1000_price_high'
 'leisure_count_500 leisure_count_1000'
 'leisure_count_500 market_count_1000' 'leisure_count_500 trc_sqm_2000'
 'leisure_count_500 sport_count_2000' 'green_part_1000^2'
 'green_part_1000 office_sqm_1000'
 'green_part_1000 cafe_count_1000_price_high'
 'green_part_1000 leisure_count_1000' 'green_part_1000 market_count_1000'
 'green_part_1000 trc_sqm_2000' 'green_part_1000 sport_count_2000'
 'office_sqm_1000^2' 'office_sqm_1000 cafe_count_1000_price_high'
 'office_sqm_1000 leisure_count_1000' 'office_sqm_1000 market_count_1000'
 'office_sqm_1000 trc_sqm_2000' 'office_sqm_1000 sport_count_2000'
 'cafe_count_1000_price_high^2'
 'cafe_count_1000_price_high leisure_count_1000'
 'cafe_count_1000_price_high market_count_1000'
 'cafe_count_1000_price_high trc_sqm_2000'
 'cafe_count_1000_price_high sport_count_2000' 'leisure_count_1000^2'
 'leisure_count_1000 market_count_1000' 'leisure_count_1000 trc_sqm_2000'
 'leisure_count_1000 sport_count_2000' 'market_count_1000^2'
 'market_count_1000 trc_sqm_2000' 'market_count_1000 sport_count_2000'
 'trc_sqm_2000^2' 'trc_sqm_2000 sport_count_2000' 'sport_count_2000^2']
0.6310955744724178

In [105]:
X20p.shape

(181507, 231)

In [106]:
Xt20=Xt[f_20]

In [107]:
Xt20.shape

(77789, 20)

In [110]:
Xt20p=polyt_df(Xt20)

['1' 'full_sq' 'life_sq' 'floor' 'school_education_centers_top_20_raion'
 'male_f' 'build_count_monolith' 'green_zone_km' 'industrial_km'
 'church_synagogue_km' 'prom_part_500' 'trc_sqm_500'
 'cafe_count_500_price_high' 'leisure_count_500' 'green_part_1000'
 'office_sqm_1000' 'cafe_count_1000_price_high' 'leisure_count_1000'
 'market_count_1000' 'trc_sqm_2000' 'sport_count_2000' 'full_sq^2'
 'full_sq life_sq' 'full_sq floor'
 'full_sq school_education_centers_top_20_raion' 'full_sq male_f'
 'full_sq build_count_monolith' 'full_sq green_zone_km'
 'full_sq industrial_km' 'full_sq church_synagogue_km'
 'full_sq prom_part_500' 'full_sq trc_sqm_500'
 'full_sq cafe_count_500_price_high' 'full_sq leisure_count_500'
 'full_sq green_part_1000' 'full_sq office_sqm_1000'
 'full_sq cafe_count_1000_price_high' 'full_sq leisure_count_1000'
 'full_sq market_count_1000' 'full_sq trc_sqm_2000'
 'full_sq sport_count_2000' 'life_sq^2' 'life_sq floor'
 'life_sq school_education_centers_top_20_raion' 'life_sq male_f'
 'life_sq build_count_monolith' 'life_sq green_zone_km'
 'life_sq industrial_km' 'life_sq church_synagogue_km'
 'life_sq prom_part_500' 'life_sq trc_sqm_500'
 'life_sq cafe_count_500_price_high' 'life_sq leisure_count_500'
 'life_sq green_part_1000' 'life_sq office_sqm_1000'
 'life_sq cafe_count_1000_price_high' 'life_sq leisure_count_1000'
 'life_sq market_count_1000' 'life_sq trc_sqm_2000'
 'life_sq sport_count_2000' 'floor^2'
 'floor school_education_centers_top_20_raion' 'floor male_f'
 'floor build_count_monolith' 'floor green_zone_km' 'floor industrial_km'
 'floor church_synagogue_km' 'floor prom_part_500' 'floor trc_sqm_500'
 'floor cafe_count_500_price_high' 'floor leisure_count_500'
 'floor green_part_1000' 'floor office_sqm_1000'
 'floor cafe_count_1000_price_high' 'floor leisure_count_1000'
 'floor market_count_1000' 'floor trc_sqm_2000' 'floor sport_count_2000'
 'school_education_centers_top_20_raion^2'
 'school_education_centers_top_20_raion male_f'
 'school_education_centers_top_20_raion build_count_monolith'
 'school_education_centers_top_20_raion green_zone_km'
 'school_education_centers_top_20_raion industrial_km'
 'school_education_centers_top_20_raion church_synagogue_km'
 'school_education_centers_top_20_raion prom_part_500'
 'school_education_centers_top_20_raion trc_sqm_500'
 'school_education_centers_top_20_raion cafe_count_500_price_high'
 'school_education_centers_top_20_raion leisure_count_500'
 'school_education_centers_top_20_raion green_part_1000'
 'school_education_centers_top_20_raion office_sqm_1000'
 'school_education_centers_top_20_raion cafe_count_1000_price_high'
 'school_education_centers_top_20_raion leisure_count_1000'
 'school_education_centers_top_20_raion market_count_1000'
 'school_education_centers_top_20_raion trc_sqm_2000'
 'school_education_centers_top_20_raion sport_count_2000' 'male_f^2'
 'male_f build_count_monolith' 'male_f green_zone_km'
 'male_f industrial_km' 'male_f church_synagogue_km'
 'male_f prom_part_500' 'male_f trc_sqm_500'
 'male_f cafe_count_500_price_high' 'male_f leisure_count_500'
 'male_f green_part_1000' 'male_f office_sqm_1000'
 'male_f cafe_count_1000_price_high' 'male_f leisure_count_1000'
 'male_f market_count_1000' 'male_f trc_sqm_2000'
 'male_f sport_count_2000' 'build_count_monolith^2'
 'build_count_monolith green_zone_km' 'build_count_monolith industrial_km'
 'build_count_monolith church_synagogue_km'
 'build_count_monolith prom_part_500' 'build_count_monolith trc_sqm_500'
 'build_count_monolith cafe_count_500_price_high'
 'build_count_monolith leisure_count_500'
 'build_count_monolith green_part_1000'
 'build_count_monolith office_sqm_1000'
 'build_count_monolith cafe_count_1000_price_high'
 'build_count_monolith leisure_count_1000'
 'build_count_monolith market_count_1000'
 'build_count_monolith trc_sqm_2000'
 'build_count_monolith sport_count_2000' 'green_zone_km^2'
 'green_zone_km industrial_km' 'green_zone_km church_synagogue_km'
 'green_zone_km prom_part_500' 'green_zone_km trc_sqm_500'
 'green_zone_km cafe_count_500_price_high'
 'green_zone_km leisure_count_500' 'green_zone_km green_part_1000'
 'green_zone_km office_sqm_1000'
 'green_zone_km cafe_count_1000_price_high'
 'green_zone_km leisure_count_1000' 'green_zone_km market_count_1000'
 'green_zone_km trc_sqm_2000' 'green_zone_km sport_count_2000'
 'industrial_km^2' 'industrial_km church_synagogue_km'
 'industrial_km prom_part_500' 'industrial_km trc_sqm_500'
 'industrial_km cafe_count_500_price_high'
 'industrial_km leisure_count_500' 'industrial_km green_part_1000'
 'industrial_km office_sqm_1000'
 'industrial_km cafe_count_1000_price_high'
 'industrial_km leisure_count_1000' 'industrial_km market_count_1000'
 'industrial_km trc_sqm_2000' 'industrial_km sport_count_2000'
 'church_synagogue_km^2' 'church_synagogue_km prom_part_500'
 'church_synagogue_km trc_sqm_500'
 'church_synagogue_km cafe_count_500_price_high'
 'church_synagogue_km leisure_count_500'
 'church_synagogue_km green_part_1000'
 'church_synagogue_km office_sqm_1000'
 'church_synagogue_km cafe_count_1000_price_high'
 'church_synagogue_km leisure_count_1000'
 'church_synagogue_km market_count_1000'
 'church_synagogue_km trc_sqm_2000' 'church_synagogue_km sport_count_2000'
 'prom_part_500^2' 'prom_part_500 trc_sqm_500'
 'prom_part_500 cafe_count_500_price_high'
 'prom_part_500 leisure_count_500' 'prom_part_500 green_part_1000'
 'prom_part_500 office_sqm_1000'
 'prom_part_500 cafe_count_1000_price_high'
 'prom_part_500 leisure_count_1000' 'prom_part_500 market_count_1000'
 'prom_part_500 trc_sqm_2000' 'prom_part_500 sport_count_2000'
 'trc_sqm_500^2' 'trc_sqm_500 cafe_count_500_price_high'
 'trc_sqm_500 leisure_count_500' 'trc_sqm_500 green_part_1000'
 'trc_sqm_500 office_sqm_1000' 'trc_sqm_500 cafe_count_1000_price_high'
 'trc_sqm_500 leisure_count_1000' 'trc_sqm_500 market_count_1000'
 'trc_sqm_500 trc_sqm_2000' 'trc_sqm_500 sport_count_2000'
 'cafe_count_500_price_high^2'
 'cafe_count_500_price_high leisure_count_500'
 'cafe_count_500_price_high green_part_1000'
 'cafe_count_500_price_high office_sqm_1000'
 'cafe_count_500_price_high cafe_count_1000_price_high'
 'cafe_count_500_price_high leisure_count_1000'
 'cafe_count_500_price_high market_count_1000'
 'cafe_count_500_price_high trc_sqm_2000'
 'cafe_count_500_price_high sport_count_2000' 'leisure_count_500^2'
 'leisure_count_500 green_part_1000' 'leisure_count_500 office_sqm_1000'
 'leisure_count_500 cafe_count_1000_price_high'
 'leisure_count_500 leisure_count_1000'
 'leisure_count_500 market_count_1000' 'leisure_count_500 trc_sqm_2000'
 'leisure_count_500 sport_count_2000' 'green_part_1000^2'
 'green_part_1000 office_sqm_1000'
 'green_part_1000 cafe_count_1000_price_high'
 'green_part_1000 leisure_count_1000' 'green_part_1000 market_count_1000'
 'green_part_1000 trc_sqm_2000' 'green_part_1000 sport_count_2000'
 'office_sqm_1000^2' 'office_sqm_1000 cafe_count_1000_price_high'
 'office_sqm_1000 leisure_count_1000' 'office_sqm_1000 market_count_1000'
 'office_sqm_1000 trc_sqm_2000' 'office_sqm_1000 sport_count_2000'
 'cafe_count_1000_price_high^2'
 'cafe_count_1000_price_high leisure_count_1000'
 'cafe_count_1000_price_high market_count_1000'
 'cafe_count_1000_price_high trc_sqm_2000'
 'cafe_count_1000_price_high sport_count_2000' 'leisure_count_1000^2'
 'leisure_count_1000 market_count_1000' 'leisure_count_1000 trc_sqm_2000'
 'leisure_count_1000 sport_count_2000' 'market_count_1000^2'
 'market_count_1000 trc_sqm_2000' 'market_count_1000 sport_count_2000'
 'trc_sqm_2000^2' 'trc_sqm_2000 sport_count_2000' 'sport_count_2000^2']

In [111]:
yp20=LR(X20p,Xt20p)

231
181507
0.6367213650351199
[-5.85215984e+00  1.62192563e+04  1.45524767e+03  2.29047142e+05
  4.98115819e+05  7.19438218e+00  3.48179093e+04 -1.49818440e+06
  7.15404694e+05  1.89802837e+05  1.82660212e+04  5.86297762e-01
 -2.61442219e+05  1.12743296e+06  4.80238007e+04  4.66601971e+00
  2.64304416e+06  2.82726055e+05  7.08174426e+04  1.23382972e+00
  2.12001674e+05 -6.54430405e-01 -1.85569493e-01 -2.90513506e+01
 -2.92650959e+02 -1.64082196e-03 -9.09949305e+00 -7.26989191e+02
 -9.39166378e+01 -1.55795280e+02 -1.58792303e+01 -1.37103466e-03
 -1.90551170e+02 -2.36572703e+02 -4.13053118e+00 -4.54495403e-04
 -1.73875167e+02 -4.79956043e+01 -3.28752470e+02 -1.77227703e-04
  4.56857982e-02 -5.87093728e-02 -6.36959526e+00 -1.81347509e+01
 -2.42184400e-04 -4.69670207e+00 -3.39453640e+02 -3.27910590e+01
 -3.76725560e+01  6.62876646e-01  2.71819295e-04 -7.38615520e+01
 -9.97357435e+00  6.08422792e-01  6.15277859e-05  3.26606416e+01
 -5.29601247e+00  2.10541150e+00  1.65743142e-04  1.90941010e+01
  3.22565680e+02 -1.30054691e+04 -4.16340842e-02  1.90102136e+02
 -3.79351315e+03 -2.14026536e+03  4.88775226e+02 -8.83906500e+02
 -1.66876373e-02  1.74864132e+04 -4.58409675e+03 -5.21747141e+02
 -1.96324048e-02 -2.33106253e+03 -7.09993611e+02 -2.91696301e+03
 -5.88847172e-03  6.24818762e+02  5.43816362e+05  4.53524074e-01
 -8.60041968e+03  3.34653983e+05  2.44784619e+04  1.87546807e+05
  6.39954284e+03 -1.14138861e+00  3.02067076e+04  3.72230164e+04
 -2.77232061e+03 -3.69127512e-01  3.57263338e+05  1.23650238e+04
 -2.16510911e+05 -3.56779383e-01 -4.07794017e+04 -9.70374094e-06
  2.65124369e-02  1.54315838e+00 -2.27109648e-01  1.88998592e-01
 -4.37262079e-02  2.20094807e-06  1.02960291e+00  1.21145441e-02
  7.71256690e-03  1.51427230e-07 -4.70414142e-02  7.17828146e-02
  7.24829482e-01  2.55182385e-07  2.94092676e-02 -1.78843402e+02
  2.84357880e+03  1.90356287e+03 -8.46387326e+02 -1.04552295e+02
 -1.47482909e-02 -8.53803539e+01  8.64938564e+02  1.15888048e+02
 -1.39422242e-02 -1.56148337e+03  2.66526365e+01 -8.91256493e+02
  1.80282605e-02  7.62065471e+02  1.02350177e+06 -1.80245831e+04
 -2.07370811e+05  8.96978736e+03  9.69409864e-01  6.55045034e+05
 -1.68100579e+05  6.41603685e+03  9.19700053e-01 -7.88446123e+04
  6.49837731e+04 -6.06344522e+04  3.16790892e-01  1.86795754e+04
  1.17107992e+04 -3.01437518e+04 -1.28193378e+03 -1.14107035e-01
 -5.63742469e+03 -1.64798609e+04 -4.74298873e+03  7.35159969e-02
 -1.91376791e+04 -1.12010110e+04  3.16763515e+04  1.72190133e-01
  8.22002695e+03 -1.67053936e+03  3.07354207e+03  6.22494447e-02
  6.92883085e+04 -2.68045678e+04 -1.73351860e+03 -3.38578333e-02
  2.05980399e+04 -7.01613871e+03  1.41339999e+04  2.15304910e-01
  1.01119392e+04  1.55053624e+02  2.35614560e-02  7.02494647e+03
  3.31393485e+03 -2.53213168e+02  1.86510152e-02 -1.45053383e+03
 -4.47568078e+02 -1.51077414e+02  2.08865744e-03  1.40296858e+02
  2.43468094e-06 -5.18271606e-01 -1.93800746e-01  1.88331060e-02
  7.14790076e-08  7.53756102e-02  7.59456622e-03 -8.02820355e-02
 -5.39585017e-07 -1.12750217e-02  2.18507751e+05  7.94421563e+04
  2.94050566e+04 -9.17906313e-01 -2.60001522e+05 -1.04032109e+04
  1.51140022e+04  1.98575462e-02 -3.58461830e+04  2.90701590e+04
  1.64458246e+03  2.27971154e-02 -4.14270421e+04  8.46698565e+03
 -6.91797137e+04 -1.09793176e-01  6.56900073e+03 -3.89030913e+02
  8.53764679e-03 -1.97943911e+03  2.01916154e+02  4.45172280e+03
 -1.73677641e-03  1.58882036e+02 -3.16620572e-07 -4.36823681e-02
  4.74715878e-02  4.42217636e-02 -7.73812644e-07 -5.61325498e-02
 -9.11322690e+04 -1.95576267e+04  2.89961404e-01  8.92425396e-03
 -1.98119165e+04  1.13688046e+03  2.83542206e+04 -6.86437112e-02
 -2.19943089e+03  8.19311685e+04 -2.28504398e-02  1.01853003e+03
 -3.43439751e-07 -4.07416772e-02 -3.63315031e+03]
232384.31295545585
Mean squared error: 173167874789009.84
R2: 0.64
0.6362584365304894

In [113]:
f_25=f_sel(X2,25)
X25=X2[f_25]
X25p = poly_df(X25)

['full_sq' 'life_sq' 'floor' 'school_education_centers_top_20_raion'
 'male_f' 'build_count_monolith' 'green_zone_km' 'industrial_km'
 'church_synagogue_km' 'green_part_500' 'prom_part_500' 'trc_sqm_500'
 'cafe_count_500_price_1000' 'cafe_count_500_price_1500'
 'cafe_count_500_price_high' 'leisure_count_500' 'green_part_1000'
 'office_sqm_1000' 'cafe_count_1000_price_high' 'leisure_count_1000'
 'market_count_1000' 'trc_sqm_2000' 'sport_count_2000' 'ecology_no data'
 'ecology_satisfactory']
0.6161188947585483
['1' 'full_sq' 'life_sq' 'floor' 'school_education_centers_top_20_raion'
 'male_f' 'build_count_monolith' 'green_zone_km' 'industrial_km'
 'church_synagogue_km' 'green_part_500' 'prom_part_500' 'trc_sqm_500'
 'cafe_count_500_price_1000' 'cafe_count_500_price_1500'
 'cafe_count_500_price_high' 'leisure_count_500' 'green_part_1000'
 'office_sqm_1000' 'cafe_count_1000_price_high' 'leisure_count_1000'
 'market_count_1000' 'trc_sqm_2000' 'sport_count_2000' 'ecology_no data'
 'ecology_satisfactory' 'full_sq^2' 'full_sq life_sq' 'full_sq floor'
 'full_sq school_education_centers_top_20_raion' 'full_sq male_f'
 'full_sq build_count_monolith' 'full_sq green_zone_km'
 'full_sq industrial_km' 'full_sq church_synagogue_km'
 'full_sq green_part_500' 'full_sq prom_part_500' 'full_sq trc_sqm_500'
 'full_sq cafe_count_500_price_1000' 'full_sq cafe_count_500_price_1500'
 'full_sq cafe_count_500_price_high' 'full_sq leisure_count_500'
 'full_sq green_part_1000' 'full_sq office_sqm_1000'
 'full_sq cafe_count_1000_price_high' 'full_sq leisure_count_1000'
 'full_sq market_count_1000' 'full_sq trc_sqm_2000'
 'full_sq sport_count_2000' 'full_sq ecology_no data'
 'full_sq ecology_satisfactory' 'life_sq^2' 'life_sq floor'
 'life_sq school_education_centers_top_20_raion' 'life_sq male_f'
 'life_sq build_count_monolith' 'life_sq green_zone_km'
 'life_sq industrial_km' 'life_sq church_synagogue_km'
 'life_sq green_part_500' 'life_sq prom_part_500' 'life_sq trc_sqm_500'
 'life_sq cafe_count_500_price_1000' 'life_sq cafe_count_500_price_1500'
 'life_sq cafe_count_500_price_high' 'life_sq leisure_count_500'
 'life_sq green_part_1000' 'life_sq office_sqm_1000'
 'life_sq cafe_count_1000_price_high' 'life_sq leisure_count_1000'
 'life_sq market_count_1000' 'life_sq trc_sqm_2000'
 'life_sq sport_count_2000' 'life_sq ecology_no data'
 'life_sq ecology_satisfactory' 'floor^2'
 'floor school_education_centers_top_20_raion' 'floor male_f'
 'floor build_count_monolith' 'floor green_zone_km' 'floor industrial_km'
 'floor church_synagogue_km' 'floor green_part_500' 'floor prom_part_500'
 'floor trc_sqm_500' 'floor cafe_count_500_price_1000'
 'floor cafe_count_500_price_1500' 'floor cafe_count_500_price_high'
 'floor leisure_count_500' 'floor green_part_1000' 'floor office_sqm_1000'
 'floor cafe_count_1000_price_high' 'floor leisure_count_1000'
 'floor market_count_1000' 'floor trc_sqm_2000' 'floor sport_count_2000'
 'floor ecology_no data' 'floor ecology_satisfactory'
 'school_education_centers_top_20_raion^2'
 'school_education_centers_top_20_raion male_f'
 'school_education_centers_top_20_raion build_count_monolith'
 'school_education_centers_top_20_raion green_zone_km'
 'school_education_centers_top_20_raion industrial_km'
 'school_education_centers_top_20_raion church_synagogue_km'
 'school_education_centers_top_20_raion green_part_500'
 'school_education_centers_top_20_raion prom_part_500'
 'school_education_centers_top_20_raion trc_sqm_500'
 'school_education_centers_top_20_raion cafe_count_500_price_1000'
 'school_education_centers_top_20_raion cafe_count_500_price_1500'
 'school_education_centers_top_20_raion cafe_count_500_price_high'
 'school_education_centers_top_20_raion leisure_count_500'
 'school_education_centers_top_20_raion green_part_1000'
 'school_education_centers_top_20_raion office_sqm_1000'
 'school_education_centers_top_20_raion cafe_count_1000_price_high'
 'school_education_centers_top_20_raion leisure_count_1000'
 'school_education_centers_top_20_raion market_count_1000'
 'school_education_centers_top_20_raion trc_sqm_2000'
 'school_education_centers_top_20_raion sport_count_2000'
 'school_education_centers_top_20_raion ecology_no data'
 'school_education_centers_top_20_raion ecology_satisfactory' 'male_f^2'
 'male_f build_count_monolith' 'male_f green_zone_km'
 'male_f industrial_km' 'male_f church_synagogue_km'
 'male_f green_part_500' 'male_f prom_part_500' 'male_f trc_sqm_500'
 'male_f cafe_count_500_price_1000' 'male_f cafe_count_500_price_1500'
 'male_f cafe_count_500_price_high' 'male_f leisure_count_500'
 'male_f green_part_1000' 'male_f office_sqm_1000'
 'male_f cafe_count_1000_price_high' 'male_f leisure_count_1000'
 'male_f market_count_1000' 'male_f trc_sqm_2000'
 'male_f sport_count_2000' 'male_f ecology_no data'
 'male_f ecology_satisfactory' 'build_count_monolith^2'
 'build_count_monolith green_zone_km' 'build_count_monolith industrial_km'
 'build_count_monolith church_synagogue_km'
 'build_count_monolith green_part_500'
 'build_count_monolith prom_part_500' 'build_count_monolith trc_sqm_500'
 'build_count_monolith cafe_count_500_price_1000'
 'build_count_monolith cafe_count_500_price_1500'
 'build_count_monolith cafe_count_500_price_high'
 'build_count_monolith leisure_count_500'
 'build_count_monolith green_part_1000'
 'build_count_monolith office_sqm_1000'
 'build_count_monolith cafe_count_1000_price_high'
 'build_count_monolith leisure_count_1000'
 'build_count_monolith market_count_1000'
 'build_count_monolith trc_sqm_2000'
 'build_count_monolith sport_count_2000'
 'build_count_monolith ecology_no data'
 'build_count_monolith ecology_satisfactory' 'green_zone_km^2'
 'green_zone_km industrial_km' 'green_zone_km church_synagogue_km'
 'green_zone_km green_part_500' 'green_zone_km prom_part_500'
 'green_zone_km trc_sqm_500' 'green_zone_km cafe_count_500_price_1000'
 'green_zone_km cafe_count_500_price_1500'
 'green_zone_km cafe_count_500_price_high'
 'green_zone_km leisure_count_500' 'green_zone_km green_part_1000'
 'green_zone_km office_sqm_1000'
 'green_zone_km cafe_count_1000_price_high'
 'green_zone_km leisure_count_1000' 'green_zone_km market_count_1000'
 'green_zone_km trc_sqm_2000' 'green_zone_km sport_count_2000'
 'green_zone_km ecology_no data' 'green_zone_km ecology_satisfactory'
 'industrial_km^2' 'industrial_km church_synagogue_km'
 'industrial_km green_part_500' 'industrial_km prom_part_500'
 'industrial_km trc_sqm_500' 'industrial_km cafe_count_500_price_1000'
 'industrial_km cafe_count_500_price_1500'
 'industrial_km cafe_count_500_price_high'
 'industrial_km leisure_count_500' 'industrial_km green_part_1000'
 'industrial_km office_sqm_1000'
 'industrial_km cafe_count_1000_price_high'
 'industrial_km leisure_count_1000' 'industrial_km market_count_1000'
 'industrial_km trc_sqm_2000' 'industrial_km sport_count_2000'
 'industrial_km ecology_no data' 'industrial_km ecology_satisfactory'
 'church_synagogue_km^2' 'church_synagogue_km green_part_500'
 'church_synagogue_km prom_part_500' 'church_synagogue_km trc_sqm_500'
 'church_synagogue_km cafe_count_500_price_1000'
 'church_synagogue_km cafe_count_500_price_1500'
 'church_synagogue_km cafe_count_500_price_high'
 'church_synagogue_km leisure_count_500'
 'church_synagogue_km green_part_1000'
 'church_synagogue_km office_sqm_1000'
 'church_synagogue_km cafe_count_1000_price_high'
 'church_synagogue_km leisure_count_1000'
 'church_synagogue_km market_count_1000'
 'church_synagogue_km trc_sqm_2000' 'church_synagogue_km sport_count_2000'
 'church_synagogue_km ecology_no data'
 'church_synagogue_km ecology_satisfactory' 'green_part_500^2'
 'green_part_500 prom_part_500' 'green_part_500 trc_sqm_500'
 'green_part_500 cafe_count_500_price_1000'
 'green_part_500 cafe_count_500_price_1500'
 'green_part_500 cafe_count_500_price_high'
 'green_part_500 leisure_count_500' 'green_part_500 green_part_1000'
 'green_part_500 office_sqm_1000'
 'green_part_500 cafe_count_1000_price_high'
 'green_part_500 leisure_count_1000' 'green_part_500 market_count_1000'
 'green_part_500 trc_sqm_2000' 'green_part_500 sport_count_2000'
 'green_part_500 ecology_no data' 'green_part_500 ecology_satisfactory'
 'prom_part_500^2' 'prom_part_500 trc_sqm_500'
 'prom_part_500 cafe_count_500_price_1000'
 'prom_part_500 cafe_count_500_price_1500'
 'prom_part_500 cafe_count_500_price_high'
 'prom_part_500 leisure_count_500' 'prom_part_500 green_part_1000'
 'prom_part_500 office_sqm_1000'
 'prom_part_500 cafe_count_1000_price_high'
 'prom_part_500 leisure_count_1000' 'prom_part_500 market_count_1000'
 'prom_part_500 trc_sqm_2000' 'prom_part_500 sport_count_2000'
 'prom_part_500 ecology_no data' 'prom_part_500 ecology_satisfactory'
 'trc_sqm_500^2' 'trc_sqm_500 cafe_count_500_price_1000'
 'trc_sqm_500 cafe_count_500_price_1500'
 'trc_sqm_500 cafe_count_500_price_high' 'trc_sqm_500 leisure_count_500'
 'trc_sqm_500 green_part_1000' 'trc_sqm_500 office_sqm_1000'
 'trc_sqm_500 cafe_count_1000_price_high' 'trc_sqm_500 leisure_count_1000'
 'trc_sqm_500 market_count_1000' 'trc_sqm_500 trc_sqm_2000'
 'trc_sqm_500 sport_count_2000' 'trc_sqm_500 ecology_no data'
 'trc_sqm_500 ecology_satisfactory' 'cafe_count_500_price_1000^2'
 'cafe_count_500_price_1000 cafe_count_500_price_1500'
 'cafe_count_500_price_1000 cafe_count_500_price_high'
 'cafe_count_500_price_1000 leisure_count_500'
 'cafe_count_500_price_1000 green_part_1000'
 'cafe_count_500_price_1000 office_sqm_1000'
 'cafe_count_500_price_1000 cafe_count_1000_price_high'
 'cafe_count_500_price_1000 leisure_count_1000'
 'cafe_count_500_price_1000 market_count_1000'
 'cafe_count_500_price_1000 trc_sqm_2000'
 'cafe_count_500_price_1000 sport_count_2000'
 'cafe_count_500_price_1000 ecology_no data'
 'cafe_count_500_price_1000 ecology_satisfactory'
 'cafe_count_500_price_1500^2'
 'cafe_count_500_price_1500 cafe_count_500_price_high'
 'cafe_count_500_price_1500 leisure_count_500'
 'cafe_count_500_price_1500 green_part_1000'
 'cafe_count_500_price_1500 office_sqm_1000'
 'cafe_count_500_price_1500 cafe_count_1000_price_high'
 'cafe_count_500_price_1500 leisure_count_1000'
 'cafe_count_500_price_1500 market_count_1000'
 'cafe_count_500_price_1500 trc_sqm_2000'
 'cafe_count_500_price_1500 sport_count_2000'
 'cafe_count_500_price_1500 ecology_no data'
 'cafe_count_500_price_1500 ecology_satisfactory'
 'cafe_count_500_price_high^2'
 'cafe_count_500_price_high leisure_count_500'
 'cafe_count_500_price_high green_part_1000'
 'cafe_count_500_price_high office_sqm_1000'
 'cafe_count_500_price_high cafe_count_1000_price_high'
 'cafe_count_500_price_high leisure_count_1000'
 'cafe_count_500_price_high market_count_1000'
 'cafe_count_500_price_high trc_sqm_2000'
 'cafe_count_500_price_high sport_count_2000'
 'cafe_count_500_price_high ecology_no data'
 'cafe_count_500_price_high ecology_satisfactory' 'leisure_count_500^2'
 'leisure_count_500 green_part_1000' 'leisure_count_500 office_sqm_1000'
 'leisure_count_500 cafe_count_1000_price_high'
 'leisure_count_500 leisure_count_1000'
 'leisure_count_500 market_count_1000' 'leisure_count_500 trc_sqm_2000'
 'leisure_count_500 sport_count_2000' 'leisure_count_500 ecology_no data'
 'leisure_count_500 ecology_satisfactory' 'green_part_1000^2'
 'green_part_1000 office_sqm_1000'
 'green_part_1000 cafe_count_1000_price_high'
 'green_part_1000 leisure_count_1000' 'green_part_1000 market_count_1000'
 'green_part_1000 trc_sqm_2000' 'green_part_1000 sport_count_2000'
 'green_part_1000 ecology_no data' 'green_part_1000 ecology_satisfactory'
 'office_sqm_1000^2' 'office_sqm_1000 cafe_count_1000_price_high'
 'office_sqm_1000 leisure_count_1000' 'office_sqm_1000 market_count_1000'
 'office_sqm_1000 trc_sqm_2000' 'office_sqm_1000 sport_count_2000'
 'office_sqm_1000 ecology_no data' 'office_sqm_1000 ecology_satisfactory'
 'cafe_count_1000_price_high^2'
 'cafe_count_1000_price_high leisure_count_1000'
 'cafe_count_1000_price_high market_count_1000'
 'cafe_count_1000_price_high trc_sqm_2000'
 'cafe_count_1000_price_high sport_count_2000'
 'cafe_count_1000_price_high ecology_no data'
 'cafe_count_1000_price_high ecology_satisfactory' 'leisure_count_1000^2'
 'leisure_count_1000 market_count_1000' 'leisure_count_1000 trc_sqm_2000'
 'leisure_count_1000 sport_count_2000'
 'leisure_count_1000 ecology_no data'
 'leisure_count_1000 ecology_satisfactory' 'market_count_1000^2'
 'market_count_1000 trc_sqm_2000' 'market_count_1000 sport_count_2000'
 'market_count_1000 ecology_no data'
 'market_count_1000 ecology_satisfactory' 'trc_sqm_2000^2'
 'trc_sqm_2000 sport_count_2000' 'trc_sqm_2000 ecology_no data'
 'trc_sqm_2000 ecology_satisfactory' 'sport_count_2000^2'
 'sport_count_2000 ecology_no data'
 'sport_count_2000 ecology_satisfactory' 'ecology_no data^2'
 'ecology_no data ecology_satisfactory' 'ecology_satisfactory^2']
0.6311838706303636

In [114]:
f_30=f_sel(X2,30)
X30=X2[f_30]
X30p = poly_df(X30)

['full_sq' 'life_sq' 'floor' 'school_education_centers_top_20_raion'
 'male_f' 'build_count_monolith' 'green_zone_km' 'industrial_km'
 'church_synagogue_km' 'green_part_500' 'prom_part_500' 'trc_sqm_500'
 'cafe_count_500_price_1000' 'cafe_count_500_price_1500'
 'cafe_count_500_price_high' 'leisure_count_500' 'market_count_500'
 'green_part_1000' 'prom_part_1000' 'office_count_1000' 'office_sqm_1000'
 'cafe_count_1000_price_high' 'leisure_count_1000' 'market_count_1000'
 'trc_sqm_2000' 'sport_count_2000' 'big_market_raion_no' 'water_1line_no'
 'ecology_no data' 'ecology_satisfactory']
0.6171387139372719
['1' 'full_sq' 'life_sq' 'floor' 'school_education_centers_top_20_raion'
 'male_f' 'build_count_monolith' 'green_zone_km' 'industrial_km'
 'church_synagogue_km' 'green_part_500' 'prom_part_500' 'trc_sqm_500'
 'cafe_count_500_price_1000' 'cafe_count_500_price_1500'
 'cafe_count_500_price_high' 'leisure_count_500' 'market_count_500'
 'green_part_1000' 'prom_part_1000' 'office_count_1000' 'office_sqm_1000'
 'cafe_count_1000_price_high' 'leisure_count_1000' 'market_count_1000'
 'trc_sqm_2000' 'sport_count_2000' 'big_market_raion_no' 'water_1line_no'
 'ecology_no data' 'ecology_satisfactory' 'full_sq^2' 'full_sq life_sq'
 'full_sq floor' 'full_sq school_education_centers_top_20_raion'
 'full_sq male_f' 'full_sq build_count_monolith' 'full_sq green_zone_km'
 'full_sq industrial_km' 'full_sq church_synagogue_km'
 'full_sq green_part_500' 'full_sq prom_part_500' 'full_sq trc_sqm_500'
 'full_sq cafe_count_500_price_1000' 'full_sq cafe_count_500_price_1500'
 'full_sq cafe_count_500_price_high' 'full_sq leisure_count_500'
 'full_sq market_count_500' 'full_sq green_part_1000'
 'full_sq prom_part_1000' 'full_sq office_count_1000'
 'full_sq office_sqm_1000' 'full_sq cafe_count_1000_price_high'
 'full_sq leisure_count_1000' 'full_sq market_count_1000'
 'full_sq trc_sqm_2000' 'full_sq sport_count_2000'
 'full_sq big_market_raion_no' 'full_sq water_1line_no'
 'full_sq ecology_no data' 'full_sq ecology_satisfactory' 'life_sq^2'
 'life_sq floor' 'life_sq school_education_centers_top_20_raion'
 'life_sq male_f' 'life_sq build_count_monolith' 'life_sq green_zone_km'
 'life_sq industrial_km' 'life_sq church_synagogue_km'
 'life_sq green_part_500' 'life_sq prom_part_500' 'life_sq trc_sqm_500'
 'life_sq cafe_count_500_price_1000' 'life_sq cafe_count_500_price_1500'
 'life_sq cafe_count_500_price_high' 'life_sq leisure_count_500'
 'life_sq market_count_500' 'life_sq green_part_1000'
 'life_sq prom_part_1000' 'life_sq office_count_1000'
 'life_sq office_sqm_1000' 'life_sq cafe_count_1000_price_high'
 'life_sq leisure_count_1000' 'life_sq market_count_1000'
 'life_sq trc_sqm_2000' 'life_sq sport_count_2000'
 'life_sq big_market_raion_no' 'life_sq water_1line_no'
 'life_sq ecology_no data' 'life_sq ecology_satisfactory' 'floor^2'
 'floor school_education_centers_top_20_raion' 'floor male_f'
 'floor build_count_monolith' 'floor green_zone_km' 'floor industrial_km'
 'floor church_synagogue_km' 'floor green_part_500' 'floor prom_part_500'
 'floor trc_sqm_500' 'floor cafe_count_500_price_1000'
 'floor cafe_count_500_price_1500' 'floor cafe_count_500_price_high'
 'floor leisure_count_500' 'floor market_count_500'
 'floor green_part_1000' 'floor prom_part_1000' 'floor office_count_1000'
 'floor office_sqm_1000' 'floor cafe_count_1000_price_high'
 'floor leisure_count_1000' 'floor market_count_1000' 'floor trc_sqm_2000'
 'floor sport_count_2000' 'floor big_market_raion_no'
 'floor water_1line_no' 'floor ecology_no data'
 'floor ecology_satisfactory' 'school_education_centers_top_20_raion^2'
 'school_education_centers_top_20_raion male_f'
 'school_education_centers_top_20_raion build_count_monolith'
 'school_education_centers_top_20_raion green_zone_km'
 'school_education_centers_top_20_raion industrial_km'
 'school_education_centers_top_20_raion church_synagogue_km'
 'school_education_centers_top_20_raion green_part_500'
 'school_education_centers_top_20_raion prom_part_500'
 'school_education_centers_top_20_raion trc_sqm_500'
 'school_education_centers_top_20_raion cafe_count_500_price_1000'
 'school_education_centers_top_20_raion cafe_count_500_price_1500'
 'school_education_centers_top_20_raion cafe_count_500_price_high'
 'school_education_centers_top_20_raion leisure_count_500'
 'school_education_centers_top_20_raion market_count_500'
 'school_education_centers_top_20_raion green_part_1000'
 'school_education_centers_top_20_raion prom_part_1000'
 'school_education_centers_top_20_raion office_count_1000'
 'school_education_centers_top_20_raion office_sqm_1000'
 'school_education_centers_top_20_raion cafe_count_1000_price_high'
 'school_education_centers_top_20_raion leisure_count_1000'
 'school_education_centers_top_20_raion market_count_1000'
 'school_education_centers_top_20_raion trc_sqm_2000'
 'school_education_centers_top_20_raion sport_count_2000'
 'school_education_centers_top_20_raion big_market_raion_no'
 'school_education_centers_top_20_raion water_1line_no'
 'school_education_centers_top_20_raion ecology_no data'
 'school_education_centers_top_20_raion ecology_satisfactory' 'male_f^2'
 'male_f build_count_monolith' 'male_f green_zone_km'
 'male_f industrial_km' 'male_f church_synagogue_km'
 'male_f green_part_500' 'male_f prom_part_500' 'male_f trc_sqm_500'
 'male_f cafe_count_500_price_1000' 'male_f cafe_count_500_price_1500'
 'male_f cafe_count_500_price_high' 'male_f leisure_count_500'
 'male_f market_count_500' 'male_f green_part_1000'
 'male_f prom_part_1000' 'male_f office_count_1000'
 'male_f office_sqm_1000' 'male_f cafe_count_1000_price_high'
 'male_f leisure_count_1000' 'male_f market_count_1000'
 'male_f trc_sqm_2000' 'male_f sport_count_2000'
 'male_f big_market_raion_no' 'male_f water_1line_no'
 'male_f ecology_no data' 'male_f ecology_satisfactory'
 'build_count_monolith^2' 'build_count_monolith green_zone_km'
 'build_count_monolith industrial_km'
 'build_count_monolith church_synagogue_km'
 'build_count_monolith green_part_500'
 'build_count_monolith prom_part_500' 'build_count_monolith trc_sqm_500'
 'build_count_monolith cafe_count_500_price_1000'
 'build_count_monolith cafe_count_500_price_1500'
 'build_count_monolith cafe_count_500_price_high'
 'build_count_monolith leisure_count_500'
 'build_count_monolith market_count_500'
 'build_count_monolith green_part_1000'
 'build_count_monolith prom_part_1000'
 'build_count_monolith office_count_1000'
 'build_count_monolith office_sqm_1000'
 'build_count_monolith cafe_count_1000_price_high'
 'build_count_monolith leisure_count_1000'
 'build_count_monolith market_count_1000'
 'build_count_monolith trc_sqm_2000'
 'build_count_monolith sport_count_2000'
 'build_count_monolith big_market_raion_no'
 'build_count_monolith water_1line_no'
 'build_count_monolith ecology_no data'
 'build_count_monolith ecology_satisfactory' 'green_zone_km^2'
 'green_zone_km industrial_km' 'green_zone_km church_synagogue_km'
 'green_zone_km green_part_500' 'green_zone_km prom_part_500'
 'green_zone_km trc_sqm_500' 'green_zone_km cafe_count_500_price_1000'
 'green_zone_km cafe_count_500_price_1500'
 'green_zone_km cafe_count_500_price_high'
 'green_zone_km leisure_count_500' 'green_zone_km market_count_500'
 'green_zone_km green_part_1000' 'green_zone_km prom_part_1000'
 'green_zone_km office_count_1000' 'green_zone_km office_sqm_1000'
 'green_zone_km cafe_count_1000_price_high'
 'green_zone_km leisure_count_1000' 'green_zone_km market_count_1000'
 'green_zone_km trc_sqm_2000' 'green_zone_km sport_count_2000'
 'green_zone_km big_market_raion_no' 'green_zone_km water_1line_no'
 'green_zone_km ecology_no data' 'green_zone_km ecology_satisfactory'
 'industrial_km^2' 'industrial_km church_synagogue_km'
 'industrial_km green_part_500' 'industrial_km prom_part_500'
 'industrial_km trc_sqm_500' 'industrial_km cafe_count_500_price_1000'
 'industrial_km cafe_count_500_price_1500'
 'industrial_km cafe_count_500_price_high'
 'industrial_km leisure_count_500' 'industrial_km market_count_500'
 'industrial_km green_part_1000' 'industrial_km prom_part_1000'
 'industrial_km office_count_1000' 'industrial_km office_sqm_1000'
 'industrial_km cafe_count_1000_price_high'
 'industrial_km leisure_count_1000' 'industrial_km market_count_1000'
 'industrial_km trc_sqm_2000' 'industrial_km sport_count_2000'
 'industrial_km big_market_raion_no' 'industrial_km water_1line_no'
 'industrial_km ecology_no data' 'industrial_km ecology_satisfactory'
 'church_synagogue_km^2' 'church_synagogue_km green_part_500'
 'church_synagogue_km prom_part_500' 'church_synagogue_km trc_sqm_500'
 'church_synagogue_km cafe_count_500_price_1000'
 'church_synagogue_km cafe_count_500_price_1500'
 'church_synagogue_km cafe_count_500_price_high'
 'church_synagogue_km leisure_count_500'
 'church_synagogue_km market_count_500'
 'church_synagogue_km green_part_1000'
 'church_synagogue_km prom_part_1000'
 'church_synagogue_km office_count_1000'
 'church_synagogue_km office_sqm_1000'
 'church_synagogue_km cafe_count_1000_price_high'
 'church_synagogue_km leisure_count_1000'
 'church_synagogue_km market_count_1000'
 'church_synagogue_km trc_sqm_2000' 'church_synagogue_km sport_count_2000'
 'church_synagogue_km big_market_raion_no'
 'church_synagogue_km water_1line_no'
 'church_synagogue_km ecology_no data'
 'church_synagogue_km ecology_satisfactory' 'green_part_500^2'
 'green_part_500 prom_part_500' 'green_part_500 trc_sqm_500'
 'green_part_500 cafe_count_500_price_1000'
 'green_part_500 cafe_count_500_price_1500'
 'green_part_500 cafe_count_500_price_high'
 'green_part_500 leisure_count_500' 'green_part_500 market_count_500'
 'green_part_500 green_part_1000' 'green_part_500 prom_part_1000'
 'green_part_500 office_count_1000' 'green_part_500 office_sqm_1000'
 'green_part_500 cafe_count_1000_price_high'
 'green_part_500 leisure_count_1000' 'green_part_500 market_count_1000'
 'green_part_500 trc_sqm_2000' 'green_part_500 sport_count_2000'
 'green_part_500 big_market_raion_no' 'green_part_500 water_1line_no'
 'green_part_500 ecology_no data' 'green_part_500 ecology_satisfactory'
 'prom_part_500^2' 'prom_part_500 trc_sqm_500'
 'prom_part_500 cafe_count_500_price_1000'
 'prom_part_500 cafe_count_500_price_1500'
 'prom_part_500 cafe_count_500_price_high'
 'prom_part_500 leisure_count_500' 'prom_part_500 market_count_500'
 'prom_part_500 green_part_1000' 'prom_part_500 prom_part_1000'
 'prom_part_500 office_count_1000' 'prom_part_500 office_sqm_1000'
 'prom_part_500 cafe_count_1000_price_high'
 'prom_part_500 leisure_count_1000' 'prom_part_500 market_count_1000'
 'prom_part_500 trc_sqm_2000' 'prom_part_500 sport_count_2000'
 'prom_part_500 big_market_raion_no' 'prom_part_500 water_1line_no'
 'prom_part_500 ecology_no data' 'prom_part_500 ecology_satisfactory'
 'trc_sqm_500^2' 'trc_sqm_500 cafe_count_500_price_1000'
 'trc_sqm_500 cafe_count_500_price_1500'
 'trc_sqm_500 cafe_count_500_price_high' 'trc_sqm_500 leisure_count_500'
 'trc_sqm_500 market_count_500' 'trc_sqm_500 green_part_1000'
 'trc_sqm_500 prom_part_1000' 'trc_sqm_500 office_count_1000'
 'trc_sqm_500 office_sqm_1000' 'trc_sqm_500 cafe_count_1000_price_high'
 'trc_sqm_500 leisure_count_1000' 'trc_sqm_500 market_count_1000'
 'trc_sqm_500 trc_sqm_2000' 'trc_sqm_500 sport_count_2000'
 'trc_sqm_500 big_market_raion_no' 'trc_sqm_500 water_1line_no'
 'trc_sqm_500 ecology_no data' 'trc_sqm_500 ecology_satisfactory'
 'cafe_count_500_price_1000^2'
 'cafe_count_500_price_1000 cafe_count_500_price_1500'
 'cafe_count_500_price_1000 cafe_count_500_price_high'
 'cafe_count_500_price_1000 leisure_count_500'
 'cafe_count_500_price_1000 market_count_500'
 'cafe_count_500_price_1000 green_part_1000'
 'cafe_count_500_price_1000 prom_part_1000'
 'cafe_count_500_price_1000 office_count_1000'
 'cafe_count_500_price_1000 office_sqm_1000'
 'cafe_count_500_price_1000 cafe_count_1000_price_high'
 'cafe_count_500_price_1000 leisure_count_1000'
 'cafe_count_500_price_1000 market_count_1000'
 'cafe_count_500_price_1000 trc_sqm_2000'
 'cafe_count_500_price_1000 sport_count_2000'
 'cafe_count_500_price_1000 big_market_raion_no'
 'cafe_count_500_price_1000 water_1line_no'
 'cafe_count_500_price_1000 ecology_no data'
 'cafe_count_500_price_1000 ecology_satisfactory'
 'cafe_count_500_price_1500^2'
 'cafe_count_500_price_1500 cafe_count_500_price_high'
 'cafe_count_500_price_1500 leisure_count_500'
 'cafe_count_500_price_1500 market_count_500'
 'cafe_count_500_price_1500 green_part_1000'
 'cafe_count_500_price_1500 prom_part_1000'
 'cafe_count_500_price_1500 office_count_1000'
 'cafe_count_500_price_1500 office_sqm_1000'
 'cafe_count_500_price_1500 cafe_count_1000_price_high'
 'cafe_count_500_price_1500 leisure_count_1000'
 'cafe_count_500_price_1500 market_count_1000'
 'cafe_count_500_price_1500 trc_sqm_2000'
 'cafe_count_500_price_1500 sport_count_2000'
 'cafe_count_500_price_1500 big_market_raion_no'
 'cafe_count_500_price_1500 water_1line_no'
 'cafe_count_500_price_1500 ecology_no data'
 'cafe_count_500_price_1500 ecology_satisfactory'
 'cafe_count_500_price_high^2'
 'cafe_count_500_price_high leisure_count_500'
 'cafe_count_500_price_high market_count_500'
 'cafe_count_500_price_high green_part_1000'
 'cafe_count_500_price_high prom_part_1000'
 'cafe_count_500_price_high office_count_1000'
 'cafe_count_500_price_high office_sqm_1000'
 'cafe_count_500_price_high cafe_count_1000_price_high'
 'cafe_count_500_price_high leisure_count_1000'
 'cafe_count_500_price_high market_count_1000'
 'cafe_count_500_price_high trc_sqm_2000'
 'cafe_count_500_price_high sport_count_2000'
 'cafe_count_500_price_high big_market_raion_no'
 'cafe_count_500_price_high water_1line_no'
 'cafe_count_500_price_high ecology_no data'
 'cafe_count_500_price_high ecology_satisfactory' 'leisure_count_500^2'
 'leisure_count_500 market_count_500' 'leisure_count_500 green_part_1000'
 'leisure_count_500 prom_part_1000' 'leisure_count_500 office_count_1000'
 'leisure_count_500 office_sqm_1000'
 'leisure_count_500 cafe_count_1000_price_high'
 'leisure_count_500 leisure_count_1000'
 'leisure_count_500 market_count_1000' 'leisure_count_500 trc_sqm_2000'
 'leisure_count_500 sport_count_2000'
 'leisure_count_500 big_market_raion_no'
 'leisure_count_500 water_1line_no' 'leisure_count_500 ecology_no data'
 'leisure_count_500 ecology_satisfactory' 'market_count_500^2'
 'market_count_500 green_part_1000' 'market_count_500 prom_part_1000'
 'market_count_500 office_count_1000' 'market_count_500 office_sqm_1000'
 'market_count_500 cafe_count_1000_price_high'
 'market_count_500 leisure_count_1000'
 'market_count_500 market_count_1000' 'market_count_500 trc_sqm_2000'
 'market_count_500 sport_count_2000'
 'market_count_500 big_market_raion_no' 'market_count_500 water_1line_no'
 'market_count_500 ecology_no data'
 'market_count_500 ecology_satisfactory' 'green_part_1000^2'
 'green_part_1000 prom_part_1000' 'green_part_1000 office_count_1000'
 'green_part_1000 office_sqm_1000'
 'green_part_1000 cafe_count_1000_price_high'
 'green_part_1000 leisure_count_1000' 'green_part_1000 market_count_1000'
 'green_part_1000 trc_sqm_2000' 'green_part_1000 sport_count_2000'
 'green_part_1000 big_market_raion_no' 'green_part_1000 water_1line_no'
 'green_part_1000 ecology_no data' 'green_part_1000 ecology_satisfactory'
 'prom_part_1000^2' 'prom_part_1000 office_count_1000'
 'prom_part_1000 office_sqm_1000'
 'prom_part_1000 cafe_count_1000_price_high'
 'prom_part_1000 leisure_count_1000' 'prom_part_1000 market_count_1000'
 'prom_part_1000 trc_sqm_2000' 'prom_part_1000 sport_count_2000'
 'prom_part_1000 big_market_raion_no' 'prom_part_1000 water_1line_no'
 'prom_part_1000 ecology_no data' 'prom_part_1000 ecology_satisfactory'
 'office_count_1000^2' 'office_count_1000 office_sqm_1000'
 'office_count_1000 cafe_count_1000_price_high'
 'office_count_1000 leisure_count_1000'
 'office_count_1000 market_count_1000' 'office_count_1000 trc_sqm_2000'
 'office_count_1000 sport_count_2000'
 'office_count_1000 big_market_raion_no'
 'office_count_1000 water_1line_no' 'office_count_1000 ecology_no data'
 'office_count_1000 ecology_satisfactory' 'office_sqm_1000^2'
 'office_sqm_1000 cafe_count_1000_price_high'
 'office_sqm_1000 leisure_count_1000' 'office_sqm_1000 market_count_1000'
 'office_sqm_1000 trc_sqm_2000' 'office_sqm_1000 sport_count_2000'
 'office_sqm_1000 big_market_raion_no' 'office_sqm_1000 water_1line_no'
 'office_sqm_1000 ecology_no data' 'office_sqm_1000 ecology_satisfactory'
 'cafe_count_1000_price_high^2'
 'cafe_count_1000_price_high leisure_count_1000'
 'cafe_count_1000_price_high market_count_1000'
 'cafe_count_1000_price_high trc_sqm_2000'
 'cafe_count_1000_price_high sport_count_2000'
 'cafe_count_1000_price_high big_market_raion_no'
 'cafe_count_1000_price_high water_1line_no'
 'cafe_count_1000_price_high ecology_no data'
 'cafe_count_1000_price_high ecology_satisfactory' 'leisure_count_1000^2'
 'leisure_count_1000 market_count_1000' 'leisure_count_1000 trc_sqm_2000'
 'leisure_count_1000 sport_count_2000'
 'leisure_count_1000 big_market_raion_no'
 'leisure_count_1000 water_1line_no' 'leisure_count_1000 ecology_no data'
 'leisure_count_1000 ecology_satisfactory' 'market_count_1000^2'
 'market_count_1000 trc_sqm_2000' 'market_count_1000 sport_count_2000'
 'market_count_1000 big_market_raion_no'
 'market_count_1000 water_1line_no' 'market_count_1000 ecology_no data'
 'market_count_1000 ecology_satisfactory' 'trc_sqm_2000^2'
 'trc_sqm_2000 sport_count_2000' 'trc_sqm_2000 big_market_raion_no'
 'trc_sqm_2000 water_1line_no' 'trc_sqm_2000 ecology_no data'
 'trc_sqm_2000 ecology_satisfactory' 'sport_count_2000^2'
 'sport_count_2000 big_market_raion_no' 'sport_count_2000 water_1line_no'
 'sport_count_2000 ecology_no data'
 'sport_count_2000 ecology_satisfactory' 'big_market_raion_no^2'
 'big_market_raion_no water_1line_no'
 'big_market_raion_no ecology_no data'
 'big_market_raion_no ecology_satisfactory' 'water_1line_no^2'
 'water_1line_no ecology_no data' 'water_1line_no ecology_satisfactory'
 'ecology_no data^2' 'ecology_no data ecology_satisfactory'
 'ecology_satisfactory^2']
0.6302199731005389

In [116]:
Xt.shape

(77789, 287)

# KNN

In [ ]:
X2s=scaling(X)
X2ts=scaling(Xt)


neigh = KNeighborsRegressor(n_neighbors=100)
#X2s = df[['TV','radio']]
#y = df[['sales']]
knn_reg = neigh.fit(X2s, y)
print(knn_reg.score(X2s, y))
# print(reg.coef_)
# print(reg.intercept_)
print(X2ts.shape)
y_pred = knn_reg.predict(X2s)
print("Mean squared error: %.2f" % mean_squared_error(y, y_pred))
print("Coefficient of determination: %.3f" % r2_score(y, y_pred))

y_pred_test_df = knn_reg.predict(X2ts)

Xt=pd.read_csv('test.csv')
ro=Xt['row ID']
type(ro)
row=ro.values

prd=pd.DataFrame({'row ID' : row, 'price_doc': y_pred_test_df}, index=None)

prd
prd.head()

prd.to_csv('output39.csv',index=False)

## Corss validation to find best K value

In [58]:
# X2s=scaling(X20p)
# X2ts=scaling(Xt20p)


# X2df_Scaled=X20p
X2df_Scaled=X

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from numpy import mean
cv = KFold(n_splits=10, random_state=1, shuffle=True)
reg = LinearRegression()
previous_mean = 0.6
current_mean = 0
for i in range(70,150,10):
    neigh = KNeighborsRegressor(n_neighbors=i) #Try different numbers
    # sfs = SequentialFeatureSelector(neigh, direction='forward',n_features_to_select=11)
    # sfs.fit(X2df_Scaled, yb)
    knn_reg = neigh.fit(X2df_Scaled, y)
    # features = list(sfs.get_feature_names_out())
    # X2_Red = X2df_Scaled[features]
    scores = cross_val_score(neigh, X2df_Scaled, y, cv=cv) 
    scores2 = cross_val_score(reg, X2df_Scaled, y, cv=cv) 
    current_mean = mean(scores)
    change = ((current_mean - previous_mean)/previous_mean)*100
    previous_mean = current_mean
    print("Iter: %d, Mean-KNN R2: %.4f, Mean-LR : R2: %.4f, Change: %.4f" % (i, mean(scores), mean(scores2), change))

Iter: 70, Mean-KNN R2: 0.6277, Mean-LR : R2: 0.6216, Change: 4.6156
Iter: 80, Mean-KNN R2: 0.6264, Mean-LR : R2: 0.6216, Change: -0.2030
Iter: 90, Mean-KNN R2: 0.6253, Mean-LR : R2: 0.6216, Change: -0.1801
Iter: 100, Mean-KNN R2: 0.6241, Mean-LR : R2: 0.6216, Change: -0.1860
Iter: 110, Mean-KNN R2: 0.6230, Mean-LR : R2: 0.6216, Change: -0.1857
Iter: 120, Mean-KNN R2: 0.6216, Mean-LR : R2: 0.6216, Change: -0.2131
Iter: 130, Mean-KNN R2: 0.6204, Mean-LR : R2: 0.6216, Change: -0.2048
Iter: 140, Mean-KNN R2: 0.6193, Mean-LR : R2: 0.6216, Change: -0.1733

# Random Forrest Regressor / Classifier

In [56]:
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor

# create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0,verbose=2)

# fit the regressor with x and y data
regressor.fit(X, y)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

building tree 1 of 100

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   10.2s remaining:    0.0s

building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88 of 100
building tree 89 of 100
building tree 90 of 100
building tree 91 of 100
building tree 92 of 100
building tree 93 of 100
building tree 94 of 100
building tree 95 of 100
building tree 96 of 100
building tree 97 of 100
building tree 98 of 100
building tree 99 of 100
building tree 100 of 100

[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed: 13.1min finished

RandomForestRegressor(random_state=0, verbose=2)

In [58]:
# y_pred_test_df = model.predict(Xt)

y_pred_test_df = regressor.predict(Xt)


Xto=pd.read_csv('test.csv')
ro=Xto['row ID']
type(ro)
row=ro.values

prd=pd.DataFrame({'row ID' : row, 'price_doc': y_pred_test_df}, index=None)

# prd['price_doc']

# prd['price_doc']=prd['price_doc'].astype(float)

prd
prd.head()

prd.to_csv('output45.csv',index=False)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    2.5s finished

In [59]:
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor

# create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0,verbose=2)

# fit the regressor with x and y data
regressor.fit(X2, y)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

building tree 1 of 100

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   19.3s remaining:    0.0s

building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88 of 100
building tree 89 of 100
building tree 90 of 100
building tree 91 of 100
building tree 92 of 100
building tree 93 of 100
building tree 94 of 100
building tree 95 of 100
building tree 96 of 100
building tree 97 of 100
building tree 98 of 100
building tree 99 of 100
building tree 100 of 100

[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed: 35.1min finished

RandomForestRegressor(random_state=0, verbose=2)

In [60]:
# y_pred_test_df = model.predict(Xt)

y_pred_test_df = regressor.predict(X2t)


Xto=pd.read_csv('test.csv')
ro=Xto['row ID']
type(ro)
row=ro.values

prd=pd.DataFrame({'row ID' : row, 'price_doc': y_pred_test_df}, index=None)

# prd['price_doc']

# prd['price_doc']=prd['price_doc'].astype(float)

prd
prd.head()

prd.to_csv('output46.csv',index=False)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    2.7s finished

## Finding optimal number of tress/ estimatator

In [ ]:
Xl=X2.iloc[:-170000]
yl=y.iloc[:-170000]

print(Xl.shape)
yl.shape

(11507, 149)

(11507,)

In [ ]:
yl=yl[:].astype(int)

In [74]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(oob_score=True, 
                            random_state=42, 
                            warm_start=True,
                            n_jobs=-1)




# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor

# create regressor object
# regressor = RandomForestRegressor(n_estimators = 100, random_state = 0,verbose=2)

regressor = RandomForestRegressor( random_state = 0,verbose=2)

# fit the regressor with x and y data
regressor.fit(Xl, yl)



oob_list = list()

# Iterate through all of the possibilities for 
# number of trees
for n_trees in [15, 20, 30, 40, 50, 100, 150, 200, 300, 400]:
    
    # Use this to set the number of trees
    RF.set_params(n_estimators=n_trees)

    # Fit the model
    RF.fit(Xl, yl)
    

    # Get the oob error
    oob_error = 1 - RF.oob_score_
    
    # Store it
    oob_list.append(pd.Series({'n_trees': n_trees, 'oob': oob_error}))

rf_oob_df = pd.concat(oob_list, axis=1).T.set_index('n_trees')

rf_oob_df

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s

building tree 1 of 100
building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88 of 100
building tree 89 of 100
building tree 90 of 100
building tree 91 of 100
building tree 92 of 100
building tree 93 of 100
building tree 94 of 100
building tree 95 of 100
building tree 96 of 100
building tree 97 of 100
building tree 98 of 100
building tree 99 of 100
building tree 100 of 100

[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:   11.9s finished

              oob
n_trees
15.0     0.970803
20.0     0.968812
30.0     0.967485
40.0     0.964831
50.0     0.965494
100.0    0.961513
150.0    0.964167
200.0    0.967485
300.0    0.969476
400.0    0.971466